Motion benchmarking system
RoboJackets/robocup-software pull request #1352
Opened 2019-10-05 16:22 UTC by liquidmetal9015

## Description
This is a suite of tools to perform benchmarks of robot motion and performance. To give quantifiable feedback on how well the robots are performing in as many dimensions as possible in a procedural environment.

So, there are a lot of concerning things about the way this runs right now and it needs work to really be good. 

Some issues:
One of the functions requires numpy
All end of motion metrics are broken due to the way move terminates and when they are recorded
The way some functions are called is a bit jank
Needs a whole lot of documentation all over the place
The non-basic motion tests aren't written yet
It isn't really doing anything with the outputted data
Imports are a bit jank due to some issues I was having

## Associated Issue
Issue #1318

## Design Documents
[Link](https://docs.google.com/document/d/1uA66JDNMuNfRuFQLymauNZkwIWz0kD3KOiUOSZp76vE/edit?usp=sharing)

## Steps to test
### Test Case 1
1. Look at the motion_benchmark play to figure out what you want to run
2. run RunMotionBenchmark in soccer

Expected result: You get some kind of useful information?

2019-10-29 18:21 UTC, kylestach commented
@liquidmetal9015 is this worth reviewing in its current state?

2019-10-29 23:38 UTC, Jason27chan requested changes
lmao

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/plays/testing/latency_test.py
> +class RunLatencyTest(play.Play):
comments about what the point of the file is

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/plays/testing/latency_test.py
> +import tactics.coordinated_pass
Separate imports like [here](https://github.com/RoboJackets/robocup-software/blob/staging/soccer/gameplay/plays/offense/adaptive_formation.py#L5)

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/plays/testing/motion_benchmark.py
> +import constants
separate imports like [here](https://github.com/RoboJackets/robocup-software/blob/staging/soccer/gameplay/plays/offense/adaptive_formation.py#L5)

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/plays/testing/motion_benchmark.py
> +class RunMotionBenchmark(play.Play):
Comment what's the point of the file

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/plays/testing/motion_benchmark.py
> +        pureRot = skills.benchmark.basic_motion_test.BasicMotionTest(numberOfRuns, self.benchmark)
Remove the comment and make an issue.

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/ball_proximity_test.py
> +class BallProximityTest(MotionTest):
I dont agree with adding nonfunctional code. I think you should create an issue

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/basic_motion_test.py
> +#import motion_test.MotionTest
Delete comments + extra linds

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/basic_motion_test.py
> +##Runs motion tests involving polygonal motions with or without a face command
do you mean with and without? meaning that it runs both?

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/basic_motion_test.py
> +        #print("This test has: " + str(self.positions) + " positions")
extra (?) prints. Please remove if you don't want them

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/basic_motion_test.py
> +        #if(len(self.points) == 0 or len(self.facePoints) == 1 or len(self.points) == len(self.facePoints)):
remove comments

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/basic_motion_test.py
> +    def updateDistances():
comments for method description

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/basic_motion_test.py
> +        #avgEndPosError = sum(self.posEndError) / len(self.posEndError)
Delete comments

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/basic_triangle_motion_benchmark.py
> +class BasicTriangleMotionBenchmark(BaseMotionBenchmark):
What does this class do? lmao does it do anything?

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/latency_test.py
> +import main
please import like [here](https://github.com/RoboJackets/robocup-software/blob/staging/soccer/gameplay/plays/offense/adaptive_formation.py#L5)

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/latency_test.py
> +    def execute_noise(self):
Please describe method in comment

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/latency_test.py
> +    def brokenNoise(self):
Please describe method in comment

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/motion_benchmark.py
> +import skills.move
imports

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/motion_benchmark.py
> +    def getSpeed(self):
lmao i feel like these functions (getSpeed, getAngleError, getPosError) should be implemented in c++ for every robot. correct me if im wrong though

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/motion_benchmark.py
> +    def getOvershoot(self, start, end):
Describe method in comment

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/motion_benchmark.py
> +   #     self.noiseStartPos = self.robot.pos
delete comments

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/motion_benchmark.py
> +    def on_enter_ProcessAllTests(self):
I don't know what you intended to do here, but delete extra comments after you do

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/motion_benchmark.py
> +        print("--------------------------ROLE_REQUIREMENTS_THING--------------------")
delete extra comments

2019-10-29 23:38 UTC, Jason27chan commented on soccer/gameplay/skills/benchmark/motion_test.py
> +    def calcDist(self, point1, point2):
function for distance between robocup points [here](https://github.com/RoboJackets/robocup-software/blob/staging/soccer/gameplay/robocup-py.cpp#L710)

2020-03-30 17:53 UTC, liquidmetal9015 commented
I think I'm going to rework this a bit and make some smaller PRs in the future.

2020-03-30 17:53 UTC, closed without merging