Refactor Vision to use Pose and Twist
RoboJackets/robocup-software pull request #1364
Opened 2019-10-20 17:18 UTC by Tdogb

## Description
Refactoring of Kalman filter to use Pose and Twist

## Associated Issue
Issue #1317

2019-10-20 17:29 UTC, JNeiger approved these changes

2019-10-21 03:14 UTC, kylestach requested changes
Thanks for taking the initiative on this one! The idea behind this is a lot more extensive, though: every time we have a Point for position or linear velocity combined with a double for heading or angular velocity, that should be replaced with a Pose or a Twist, respectively. I can walk you through this more on Tuesday's meeting.

Feel free to ping me with any questions on this.

2019-10-21 03:14 UTC, kylestach commented on soccer/vision/robot/KalmanRobot.cpp
> +    Geometry2d::Pose initPose(initMeasurement.getPos().x(), initMeasurement.getPos().y(), initMeasurement.getTheta());
`CameraRobot` should use `Pose` internally.

2019-10-21 03:14 UTC, kylestach commented on soccer/vision/robot/KalmanRobot.cpp
> +        initTwist.linear() = previousWorldRobot.getVel();
Most likely, `WorldRobot` should use `Pose/Twist` classes too.

2019-10-21 03:14 UTC, kylestach commented on soccer/vision/filter/KalmanFilter3D.cpp
>  }
KalmanFilter3D should have a way of getting a Pose and a Twist.

2019-11-01 18:10 UTC, kylestach approved these changes
LGTM

2019-11-01 18:13 UTC, merged