Add clear back
RoboJackets/robocup-software pull request #1391
Opened 2019-11-24 20:30 UTC by HussainGynai

## Description
See previous pull request

## Associated Issue
Issue #1331

2019-12-08 20:10 UTC, tjones320 requested changes
Pass style and then you're good!

2020-01-07 23:54 UTC, Jason27chan commented on soccer/gameplay/plays/offense/clear.py
> +        # count = 0
Delete comments

2020-01-08 00:03 UTC, tjones320 approved these changes
Is the added picture necessary?

2020-01-08 01:29 UTC, Jason27chan approved these changes

2020-01-08 01:31 UTC, merged