Created a basic play for offensive indirect kicks
RoboJackets/robocup-software pull request #1409
Opened 2020-02-05 01:56 UTC by HussainGynai

## Description
A basic offensive indirect play

## Associated Issue
Issue #1408

## Steps to test
### Test Case 1
1. Setup an indirect in the offensive half of the field 
2. Run the play
3. Observe how well it works
4. Repeat with other areas on the field

2020-02-11 23:29 UTC, Jason27chan requested changes

2020-02-11 23:29 UTC, Jason27chan commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +        # return 0 if behavior.Behavior.State.running or (
delete random comments

2020-02-11 23:29 UTC, Jason27chan commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +            self.chip = True # If the reciever is the second one, it will be far away and require a chip
You don't have to comment every line lmao. It's in there, so you don't have to take it out, but for future reference, commenting every line is pretty extra and not always helpful

2020-02-11 23:29 UTC, Jason27chan commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +            sign_sign = -1
pls change to helpful variable name

2020-02-16 19:42 UTC, Jason27chan approved these changes
You are a good person

2020-02-23 18:52 UTC, liquidmetal9015 commented
I'm getting:

INFO:root:Current play 'Stopped' no longer enabled, aborting
INFO:root:Chose new play: 'BasicIndirect'
WARNING:root:Ambiguous fsm transitions from state'State.preparing'.  The following states are reachable now: [<State.kicking: 2>, <State.failed: 4>];  Proceeding by taking the first option.
INFO:root:Current play 'BasicIndirect' finished running
INFO:root:Chose new play: 'BasicIndirect'
INFO:root:Current play 'BasicIndirect' no longer enabled, aborting

without the ball actually being kicked? The ambiguous transition is an issue.

Also Coordinated pass is failling:
    CoordinatedPass::failed
        LineKick::kick[robot=5]
            avoidBall(0.1)
            avoidBall(-1)
            avoidBall(-1)
            avoidBall(-1)
        rcv_pt=Point(0, 6.75)
        timeout=8.98

I don't know what that's about. It's possible I'm testing this wrong, also that we should have a better method of testing restarts, idk.

2020-02-23 20:37 UTC, Jason27chan requested changes
Looks good! just some small changes for doxygen

2020-02-23 20:37 UTC, Jason27chan commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +# A basic play for the Offensive Indect kick
Change # to ## for javadocs format so doxygen reads it

2020-02-23 20:37 UTC, Jason27chan commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +    def calc_pass_point(
Add javadocs

2020-02-23 20:37 UTC, Jason27chan commented on soccer/gameplay/tactics/coordinated_pass.py
>      # Funciton that decides if an opponent robot is in the way of passing
Can you change # to ## here too? Thank you God bless

2020-02-26 00:35 UTC, Jason27chan approved these changes
LGTM

2020-03-08 18:06 UTC, chachmu approved these changes
Looks pretty good, a few more typos in comments but meh :man_shrugging:

2020-03-08 18:06 UTC, chachmu commented on soccer/gameplay/plays/Clear/clear.py
>  # needs to have a unique name beyond that
![image](https://user-images.githubusercontent.com/14020373/76168349-84fc8200-6145-11ea-999c-b3092d4c895c.png)

2020-03-08 18:06 UTC, chachmu commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +        kick = 2  # Kick the ball to one of the recievers
*receiver

2020-03-08 18:06 UTC, chachmu commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +        move = 1  # Move recievers to proper postions
*receiver

2020-03-08 18:06 UTC, chachmu commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +        self.chip = False  # Determines wether to chip or not
*whether

2020-03-08 18:06 UTC, chachmu commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +        self):  # Determines the position of the recievers and where to pass
*receivers

2020-03-08 18:06 UTC, chachmu commented on soccer/gameplay/plays/restarts/basic_offensive_indirect.py
> +            self.chip = True  # If the reciever is the second one, it will be far away and require a chip
*receiver

2020-03-08 18:07 UTC, merged