Initial ROS2 refactor + Migrate vision receiver
RoboJackets/robocup-software pull request #1482
Opened 2020-06-09 05:18 UTC by oswinso

## Description
This PR:
- Rearranges `common` a bit to be easier to refactor into ROS2 packages later
    - Moves `protobuf` into its own folder
    - Changes `common` to have headers in a separate `include` folder
    - Renames `Geometry2d` to `geometry2d` to conform to Google C++ standards
- Creates a `config` system
    - `config_server` which acts as a global parameter server and serves `FieldDimensions` and `GameSettings`
    - `config_client` which pulls the most recent `FieldDimensions` and `GameSettings` and has methods to update them
- Refactors `vision_receiver` to be a separate `rclcpp::Node`
- Creates launch files to launch sim, ie. `sim.launch.py`
- (Temporarily) Refactors `Processor` to have a `_vision_receiver_sub`, `_config_client` and `_executor` just so that it can interface with the `vision_receiver` for now.

## Steps to test
### Sim still works
1. Get ROS2
2. Clone this to like `~/robocup_ros_ws/src/robocup-software`
3. `source /opt/ros/XXXX/setup.bash`. I'm on 18.04 so I tested this on eloquent
4. Run `colcon build`
5. `ros2 launch rj_robocup sim.launch.py`

Expected result: Things still run. Vision still works.

2020-06-09 06:52 UTC, JNeiger reviewed
Quick glance, I'll double check more of the ros specific stuff at another point

2020-06-09 06:52 UTC, JNeiger commented on common/include/time.hpp
> +inline rclcpp::Time ToROS(RJ::Time time) {
It might be smart to change this to ToROSTime or something since this isn't in a time namespace

2020-06-09 06:52 UTC, JNeiger commented on soccer/config_server/config_server.h
> +#pragma once
Not unique to this file, but the swap from ".hpp" -> ".h", is that some style thing?

2020-06-09 06:52 UTC, JNeiger commented on soccer/vision/ball/BallBounce.cpp
> +            // mouth is not accounted for
nit: Some of the comments in this file got messed up

2020-06-09 06:52 UTC, JNeiger commented on soccer/vision/filter/KalmanFilter2D.cpp
> +    P_k1_k1 << p, 0, 0, 0, 0, p, 0, 0, 0, 0, p, 0, 0, 0, 0, p;
The matrix initialization in here should be exempt from style IMO. They were lined up to match the matrix size

2020-06-09 06:52 UTC, JNeiger commented on soccer/vision/filter/KalmanFilter3D.cpp
> +        0, 0, 0, 0, 0, 0, s * p, 0, 0, 0, 0, 0, 0, s * p;
Matrix stuff here too

2020-06-09 14:21 UTC, oswinso commented
@JNeiger Thanks for scrolling through all those files. I think I'm going to break this PR up into multiple parts so it's not as hard to review.

2020-06-09 15:03 UTC, kylestach requested changes
So, I'm having to stop here because GitHub's mobile UI is choking on this PR. 

IMO this should be two or three separate PRs. One to do all of the style changes and renaming, one for ROS build system, and one for breaking out vision receiver.

2020-06-09 15:03 UTC, kylestach commented on common/AutoName.hpp
> -class AutoName {
Wow, I didn't even know we had this.

2020-06-09 15:03 UTC, kylestach commented on common/common/field_dimensions.cpp
> +#include <field_dimensions.h>
Why is this file not showing up as moved? Just because the class name was changed too?

2020-06-09 15:03 UTC, kylestach commented on common/common/utils.cpp
> +#include <utils.h>
I'm pretty sure ROS 2 style is .hpp for C++ headers. 

Also, for things in the same package it should be `#include "file"` IMO. Really I would prefer that for everything that's not a system header. I think either one is okay according to the style guide, I just prefer to separate system/user headers visually.

2020-06-09 15:03 UTC, kylestach commented on common/geometry2d/src/ArcTest.cpp
> +namespace geometry2d::Testing {
Should be `geometry2d::testing`

2020-06-09 16:30 UTC, JNeiger commented on common/common/utils.cpp
> +#include <utils.h>
I always liked 
<System headers>

<External libraries>

<Not this package but same project>

"This package"

I fought clang-format for a while last week setting it up to automatically order then for me if you guys want the excerpt

2020-06-11 07:22 UTC, kylestach commented on common/common/utils.cpp
> +#include <utils.h>
I agree, except for `.cpp` files where I like to have `#include "a.hpp"` all the way at the top for `a.cpp`.

2020-06-11 16:06 UTC, JNeiger commented on common/common/utils.cpp
> +#include <utils.h>
For sure

2020-06-11 16:22 UTC, JNeiger commented on common/common/utils.cpp
> +#include <utils.h>
Created #1483 if you guys want to force it using style

2020-06-29 21:32 UTC, kylestach commented
Can we close this @oswinso?

2020-06-29 21:55 UTC, closed without merging