Made ball friction constant configurable
RoboJackets/robocup-software pull request #1599
Opened 2020-11-06 01:45 UTC by kfu02

## Description
Previously, the ball friction constant in `/soccer/src/soccer/world_state.hpp` was a hardcoded value. This PR makes it configurable using the internal parameters interface.

## Associated Issue
Closes #1498

2020-11-06 18:47 UTC, kylestach requested changes
A couple of minor nits, but mostly looks good!

2020-11-06 18:47 UTC, kylestach commented on soccer/src/soccer/params.cpp
> +#include <params.hpp>
Nit: could you rename this `global_params.cpp/hpp`?

2020-11-06 18:47 UTC, kylestach commented on soccer/src/soccer/params.hpp
> +constexpr auto kSoccerParamModule = "soccer";
Nit: change this param module to `kGlobalParamModule`. We'll probably eventually be using this module in #1586.

2020-11-06 18:47 UTC, kylestach commented on soccer/src/soccer/params.cpp
> +DEFINE_NS_FLOAT64(kSoccerParamModule, soccer::physics, kBallDecayConstant, 0.180,
Nit: should be `ball_decay_constant` instead of `kBallDecayConstant`.

2020-11-06 22:51 UTC, kylestach approved these changes
Looks good to me!

2020-11-11 02:23 UTC, HussainGynai approved these changes
LGTM (don't merge yet so others can also review)

2020-11-11 04:17 UTC, spatel776 approved these changes

2020-11-22 17:38 UTC, kylestach approved these changes

2020-12-28 18:11 UTC, merged