add rosconverter detectionrobot
RoboJackets/robocup-software pull request #1612
Opened 2020-11-17 20:06 UTC by adithya-gv

## Description
Completed DetectionRobotMsg rosconverter for SSLBall

## Associated Issue
Issue #1588 

## Design Documents
N/A

## Steps to test
### Test Case 1
1.Run soccer

Expected result: No regression expected

2020-11-22 21:32 UTC, kylestach requested changes
A few fixes, looks good!

2020-11-22 21:32 UTC, kylestach commented on rj_utils/include/rj_utils/conversions.hpp
> +ASSOCIATE_CPP_ROSS(SSL_DetectionRobot, DetectionRobotMsg)
```suggestion
ASSOCIATE_CPP_ROS(SSL_DetectionRobot, DetectionRobotMsg)
```

2020-11-22 21:32 UTC, kylestach commented on rj_utils/CMakeLists.txt
> +target_dependencies(rj_utils PUBLIC rj_convert)
```suggestion
target_link_libraries(rj_utils PUBLIC rj_convert)
```

2020-11-23 21:08 UTC, adithya-gv reviewed
Thank you! Fixed these as you said!

2021-01-17 18:47 UTC, kylestach approved these changes

2021-02-02 22:45 UTC, HussainGynai approved these changes
LGTM

2021-05-25 23:12 UTC, merged