Dribble skill
RoboJackets/robocup-software pull request #1641
Opened 2021-05-19 01:35 UTC by kasohrab

## Description
Dribble skill 

## Associated Issue
Issue #???

## Design Documents
[Link](link-to-design-doc)

## Steps to test
### Test Case 1
1. Step 1
2. Step 2
3. Step 3

Expected result: working dribble action

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1 : Dribble action
- [ ] Step 2 : Dribble skill

2021-05-25 22:37 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/action/dribble.py
>          pass
This shouldn't pass, we still need it to return something, it should just return False, since we want dribble to never be done.

2021-05-25 22:37 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/action/dribble.py
> +        intent.is_active = True
Your indentation is a bit messed up here

2021-05-25 22:37 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/action/dribble.py
> +        return False;
You don't put semi-colons at the end of lines in python

2021-05-25 22:37 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/action/dribble.py
>          pass
Wait nvm you have 2 is_done functions, just delete this first one, the second one is correct.

2021-05-25 22:37 UTC, kfu02 requested changes

2021-05-25 22:37 UTC, kfu02 commented on rj_gameplay/rj_gameplay/action/dribble.py
> +        return False;
here

2021-06-03 22:28 UTC, HussainGynai approved these changes
Looks good to me, just delete the TODO and it should be good.

2021-06-03 22:28 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/skill/dribble.py
> +        # TODO: change so this properly returns the actions intent messages
You can delete this comment

2021-06-08 01:30 UTC, HussainGynai approved these changes
LGTM, good job!

2021-06-08 23:24 UTC, kfu02 approved these changes
One small detail to fix, but otherwise you're good to merge.

2021-06-08 23:24 UTC, kfu02 commented on rj_gameplay/rj_gameplay/action/dribble.py
> +            path_command.override_face_point=[Point(self.face_point[0], self.face_point[1])]
```suggestion
            path_command.override_face_point=[Point(x=self.face_point[0], y=self.face_point[1])]
```
Small bug (I assume copied over from move.py before the bugfix)

2021-06-08 23:25 UTC, kfu02 commented on rj_gameplay/rj_gameplay/action/dribble.py
> +            path_command.override_face_point=[Point(self.face_point[0], self.face_point[1])]
You can directly commit this change with the "commit suggestion" button

2021-06-09 02:54 UTC, merged