Add the global param server node and use it for some common parameters.
RoboJackets/robocup-software pull request #1645
Opened 2021-05-24 03:26 UTC by kylestach

## Description
This adds a new node (basically does nothing) to act as a global parameter server for the other nodes.

## Associated Issue
Issue #1586.

## Steps to test
### All parameters declared
1. Run simulation
2. Run `ros2 param list /parameter_blackboard`

Expected result: several parameters are listed.

### Changing parameters
1. Add some code to print `PARAM_*` for one of the global parameters
2. Change the parameter during runtime with `ros2 param set /parameter_blackboard <parameter> <value>`

Expected result: the readout should change.

2021-05-24 03:27 UTC, kylestach commented
Note: I eventually intend to put everything from `GameSettings` (https://github.com/RoboJackets/robocup-software/blob/ros2/rj_msgs/msg/GameSettings.msg) into global parameters, but we do not have that for now.

2021-05-28 17:51 UTC, kfu02 requested changes
All parameters were declared, but on trying to change a parameter I got the following error:
```
❯ ros2 param set /global_parameter_server PARAM_use_sim_time 42069
Setting parameter failed
```
Granted, I did merge in gameplay_node_update because sim kept crashing on me, perhaps I did it wrong? The only merge conflict was in `autonomy_interface.cpp`, which I handled by taking the code from this branch (gameplay_node_update had some code for "_old_soccer" nodes).

2021-05-28 18:48 UTC, kylestach commented
You should set `use_sim_time` rather than `PARAM_use_sim_time` - the `PARAM_` prefix is only in C++ code - but also, don't do `use_sim_time`. That's a ROS builtin, not something from our code. I would suggest testing `soccer.robot.max_kick_speed` (in C++ code, `soccer::robot::PARAM_max_kick_speed`) instead (remember that it's a double, so you need to set it to something like 6.0 rather than 6).

2021-05-28 19:46 UTC, kfu02 approved these changes
Expected behavior achieved, after a merge with gameplay_node_update.

2021-05-28 19:53 UTC, HussainGynai approved these changes
LGTM, just newlines

2021-05-28 19:53 UTC, HussainGynai commented on rj_param_utils/src/ros2_local_param_provider.cpp
> +}  // namespace params
\n

2021-05-28 19:53 UTC, HussainGynai commented on soccer/src/soccer/global_param_server.cpp
> +}
\n

2021-05-28 21:43 UTC, merged