Write capture skill
RoboJackets/robocup-software pull request #1646
Opened 2021-05-24 03:55 UTC by Yudai-8-om

## Description
Capture class is rewritten.
tick returns the list of actions the robot can take.
is_done function is copied from the action.

2021-06-01 21:34 UTC, kfu02 requested changes
Good start, left some comments on skill/capture.py. Also, I think the fumble/pass classifier code is from a different PR, could you remove those files from this PR? (Removing those files from this branch won't remove them from your `fumble_classifier` branch.)

2021-06-01 21:34 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/capture.py
> +        self.root.tick_once(self.robot, world_state)
Almost right, this should return a list of actions (despite the return type being None). See `skill/move.py` in gameplay_node_update: https://github.com/RoboJackets/robocup-software/blob/gameplay_node_update/rj_gameplay/rj_gameplay/skill/move.py

2021-06-01 21:34 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/capture.py
> +    	self.capture.is_done(world_state)
This should return a boolean, as per the method header. 

Again see skill/move.py in gameplay_node_update: https://github.com/RoboJackets/robocup-software/blob/gameplay_node_update/rj_gameplay/rj_gameplay/skill/move.py

2021-06-08 01:26 UTC, HussainGynai approved these changes
Looks good, just get rid of the extra files, and the one indentation issue.

2021-06-08 01:26 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/skill/capture.py
> +    	self.robot = robot
You need to fix the indentation here.

2021-06-08 23:17 UTC, closed without merging