Write capture skill
RoboJackets/robocup-software pull request #1656
Opened 2021-06-08 23:20 UTC by Yudai-8-om

## Description
capture skill

tick returns the list of actions the robot can take.
is_done function is copied from the action.

2021-06-08 23:35 UTC, kfu02 requested changes
You have a few minor changes to make. Nice job getting the git stuff sorted, though.

2021-06-08 23:35 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/capture.py
> +    	self.robot = robot
indent issue, should match the line below

2021-06-08 23:35 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/capture.py
> +    def tick(self, robot: rc.Robot, world_state: rc.WorldState) -> None:
this method should return a list of actions, see `move.py` or `mark.py` on the ros2 branch

2021-06-08 23:35 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/capture.py
> +    	self.capture.is_done(world_state)
this should return a bool, again see the move or mark skills

2021-06-09 02:35 UTC, kfu02 approved these changes
Looks good!

2021-06-10 23:24 UTC, HussainGynai approved these changes
LGTM

2021-06-10 23:24 UTC, merged