Update to new sim protocol
RoboJackets/robocup-software pull request #1657
Opened 2021-06-09 01:01 UTC by kylestach

## Description
This also includes some minor compatability fixes and reworks to match
the new simulator setup - for example, kick speeds are now specified in
m/s all the way through.

## Associated Issue
[ClickUp](https://app.clickup.com/t/vtbc83)

## Steps to test
### Regular sim run
1. Download ER-force's simulator: https://github.com/robotics-erlangen/framework
2. Build and run `simulator-cli` using their instructions
3. Comment out the `grsim` node in `sim.launch.py` and build
4. Launch sim

Expected result: Simulation runs correctly; placement works

2021-06-09 05:15 UTC, kylestach commented on soccer/src/soccer/radio/sim_radio.cpp
> +        control->mutable_teleport_ball()->set_teleport_safely(true);
```suggestion
```

2021-06-09 05:18 UTC, kylestach commented on rj_common/include/rj_common/utils.hpp
> +    return factor * a + (1 - factor) * a;
```suggestion
    return factor * a + (1 - factor) * b;
```

2021-06-13 04:31 UTC, kfu02 requested changes
Switching to ERForce works flawlessly, provided the `--realism None` flag is set for `./simulator-cli`.

Going back to grSim is a little rocky. After reverting the `sim.launch.py` edits, I ran the following:
```
rm -rf build-*
git clean -fX install/
make perf
ros2 launch rj_robocup sim.launch.py
```
which opened grSim again, but all ball/robot placement was broken, and the motion commands sent by gameplay didn't move any robots. 

I had to additionally call `./util/ubuntu-setup` before re-running all the above commands to get grSim working again. If it's an issue that can be fixed later without too much consequence in the meantime then ship it.

2021-06-15 02:04 UTC, HussainGynai requested changes
Same thing as Kevin pretty much, there are 5 extra bots on each team showing up (starting on the wrong side of the field) along the right side. Is it do with the Division Enum?

2021-06-16 23:44 UTC, kfu02 approved these changes
Approved bc the crashing issues are annoying, but not gamebreaking.

2021-06-16 23:45 UTC, HussainGynai approved these changes

2021-06-16 23:46 UTC, kylestach commented on soccer/src/soccer/radio/packet_convert.cpp
> +            sim->set_kick_angle(PARAM_chip_angle);
```suggestion
            sim->set_kick_angle(static_cast<float>(PARAM_chip_angle));
```

2021-06-16 23:46 UTC, kylestach commented on soccer/src/soccer/radio/packet_convert.cpp
> +    sim->set_dribbler_speed(PARAM_max_dribbler_speed * intent.dribbler_speed);
```suggestion
    sim->set_dribbler_speed(static_cast<float>(PARAM_max_dribbler_speed * intent.dribbler_speed));
```

2021-06-16 23:46 UTC, kylestach commented on soccer/src/soccer/radio/packet_convert.cpp
> +    sim->set_dribbler_speed(PARAM_max_dribbler_speed * manipulator.dribbler_speed);
```suggestion
    sim->set_dribbler_speed(static_cast<float>(PARAM_max_dribbler_speed * manipulator.dribbler_speed));
```

2021-06-17 00:10 UTC, merged