Basic defense play
RoboJackets/robocup-software pull request #1671
Opened 2021-06-17 16:14 UTC by kfu02

## Description
There's a surprising amount of new stuff here:
 * goalie_id from the /referee/goalie_id ROS topic is now a part of WorldState (`world_state.game_info.goalie_id`)
 * minor capture skill bug fixed
 * intercept action/skill added
 * goalie tactic added
 * basic_defense play added

## Steps to test
### Test Case 1
1. Make sure on any and all runs that robot 0 is the goalie robot (the one in the penalty box)

[other test cases TBD]

Expected result: ???

2021-06-17 16:18 UTC, kfu02 reviewed
quick comments to speed up review & a question for Kyle

2021-06-17 16:18 UTC, kfu02 commented on rj_gameplay/rj_gameplay/action/kick.py
> +        # print('robot:', robot.id, 'kicking')
this file filled in by #1644, ignore for now

2021-06-17 16:18 UTC, kfu02 commented on rj_gameplay/rj_gameplay/play/wall_ball.py
> +
this file is identical to the file merged into ros2 recently by #1661, shows here bc I ran `make pretty-lines`

2021-06-17 16:18 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/capture.py
> +    def __init__(self, robot: rc.Robot = None):
minor capture bug

2021-06-17 16:18 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/move.py
> +    def tick(self, robot: rc.Robot,
again, `make pretty-lines` the only changes here

2021-06-17 16:18 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/goalie_tactic.py
> +                self.intercept_se.skill.target_point = world_state.ball.pos
the intercept skill doesn't seem to be doing anything, @kylestach can you take a look to see if I'm missing something?

2021-06-19 02:07 UTC, HussainGynai requested changes
Some minor stuff, looks pretty good overall.

2021-06-19 02:07 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/goalie_tactic.py
> +                role_requests[self.receive_se] = [role.RoleRequest(role.Priority.HIGH, False, self.role_cost)]
This should probably have required as True instead of False

2021-06-19 02:07 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/goalie_tactic.py
> +                role_requests[self.move_se] = [role.RoleRequest(role.Priority.HIGH, False, self.role_cost)]
Same here, we probably want the goalie movements to be required.

2021-06-19 02:07 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/goalie_tactic.py
> +            skills.append(self.receive_se)
This should probably be an if else to match the logic from get_requests (also on the off chance both receive and move get assigned)

2021-06-19 02:07 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/goalie_tactic.py
> +        return self.move_se.skill.is_done(world_state)
Do we want goalie to be able to be done?

2021-06-19 03:12 UTC, kfu02 reviewed
Left a bunch of comments for files that you can skip when reviewing, at least this time around.

2021-06-19 03:12 UTC, kfu02 commented on rj_gameplay/rj_gameplay/action/intercept.py
> +"""This module contains the interface and action for intercept."""
Broken intercept, not sure if it's motion planning side or here. Feel free to skip for now since it's not used.

2021-06-19 03:12 UTC, kfu02 commented on rj_gameplay/rj_gameplay/gameplay_node.py
> +        self.goalie_id_sub = self.create_subscription(msg.Goalie,
Broken goalie sub, skip for now, will fix.

2021-06-19 03:12 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/intercept.py
> +from abc import ABC, abstractmethod
again, intercept isn't used because it's broken, feel free to skip

2021-06-19 03:12 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/wall_tactic.py
> +MIN_WALL_RAD = None
the only changes to this file from what's in #1661 are from `make pretty-lines`, skip this too

2021-06-19 03:12 UTC, kfu02 commented on rj_gameplay/stp/rc.py
> +        self.__goalie_id = goalie_id
goalie_id changes that aren't used yet, skip

2021-06-19 03:12 UTC, kfu02 commented on rj_gameplay/stp/utils/world_state_converter.py
> +    game_info = rc.GameInfo(period, state, restart, our_restart,
more goalie_id

2021-06-20 04:48 UTC, HussainGynai requested changes
Looks good, I think add a pass/clear if the goalie gets the ball, otherwise it'll just sit there.

2021-06-20 05:39 UTC, Yudai-8-om reviewed
LGTM, I agree with Hussain about adding pass/clear thing
Other than that, worked great!

2021-06-20 06:00 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/goalie_tactic.py
> +        self.pivot_kick_se = tactic.SkillEntry(pivot_kick.PivotKick(target_point = np.array([0.0, 6.0]), chip=True, kick_speed=4.0))
You should up the kick speed to like 5 or 6 so it chips further

2021-06-20 21:09 UTC, merged