Striker tactic
RoboJackets/robocup-software pull request #1672
Opened 2021-06-18 04:05 UTC by Yudai-8-om

## Description
(Premature) striker tactic.

Current function:
just capture and shoot
Targeted point is generated randomly

To-do:
Make cost function for finding a targeted point 
add more shoot patterns like receive -> shoot and dribble -> shoot?

## Steps to test

1. run sim
2. place ball somewhere on the opponent's side field
3. Robot 1 will capture and shoot.

Expected result: Goal!

## Concerns
Capture → shoot is not seamless.
Kick_speed may be needed to be tweaked.

2021-06-18 15:26 UTC, kfu02 requested changes
Looks good so far (except one small bug). Looking forward to reviewing again once you have it kicking toward goal, haha

2021-06-18 15:26 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/shoot.py
> +random_shoot = random.uniform(-0.5,0.5)
```suggestion
random_shoot = np.random.uniform(-0.5,0.5)
```

Sim doesn't launch without this

2021-06-18 15:26 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/striker_tactic.py
> +		if capture_result and capture_result[0].is_filled():
I did not know there was an `is_filled()` method. Good to know

2021-06-18 15:26 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/striker_tactic.py
> +		#  <- receive skill is not published yet
```suggestion
		#  TODO: <- receive skill is not published yet
```

2021-06-18 15:26 UTC, kfu02 commented on rj_gameplay/stp/skill/action_behavior.py
> +        if not self.world_state is None and self.action.is_done(self.world_state):
```suggestion
        if self.world_state is not None and self.action.is_done(self.world_state):
```

2021-06-19 02:23 UTC, HussainGynai requested changes

2021-06-19 02:23 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/play/striker.py
> +
I think you have some tabs or spaces on this empty line so its not a new line.

2021-06-19 02:23 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/striker_tactic.py
> +		self.cost = shoot_cost()
Add a param for a cost function in the init, so we can put in any one we want in it.

2021-06-20 05:41 UTC, HussainGynai requested changes
For me, when I test, two robots just pass between each other over and over, or one of the robots gets the ball and pivots randomly back and forth.

2021-06-21 03:36 UTC, closed without merging