removed unnecessary interface declarations from gameplay
RoboJackets/robocup-software pull request #1729
Opened 2021-09-01 01:07 UTC by hdemusg

## Description
Removing unused interfaces from gameplay Python files. 

## Associated Issue
'remove "custom" interfaces' on Clickup

## Steps to test
Run soccer to make sure it works

Expected result: It should run

2021-09-13 00:35 UTC, kfu02 requested changes
please make sure this builds

2021-09-13 00:35 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/move.py
> +<<<<<<< HEAD
fix this merge conflict

2021-09-13 00:35 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/pivot_kick.py
> +<<<<<<< HEAD
fix this merge conflict

2021-09-13 00:35 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/stub.py
>  class Stub(skill.ISkill):
remove this file please

2021-09-20 01:27 UTC, rkbard approved these changes

2021-09-20 01:55 UTC, Yudai-8-om approved these changes
LGTM!

2021-09-20 01:57 UTC, anshulm07 approved these changes
Looks good.

2021-09-22 01:00 UTC, merged