Removed HML and replaced with arbitrary floats
RoboJackets/robocup-software pull request #1733
Opened 2021-09-26 23:20 UTC by anshulm07

Removed HML and replaced all uses of HML in tactics with a float that will be changed later

2021-09-28 23:25 UTC, HussainGynai requested changes
Change and test robocup-software/rj_gameplay/tests/stp/role/test_naive_assignment.py and test_cost.py

2021-10-31 23:24 UTC, kasohrab requested changes
resolve merge conflicts

2021-11-10 00:27 UTC, kasohrab requested changes
could you run make pretty-lines to fix the style errors?

2021-11-10 00:47 UTC, HussainGynai requested changes
Fix merge errors, and don't cast to int for priority, just leave it as a float.

2021-11-10 00:47 UTC, HussainGynai commented on rj_gameplay/stp/role/assignment/naive.py
> +            key = int(request.priority)
Why change priority from float to int? Here 1.1 and 1.2 would be given the same priority, when we don't want that.

2021-11-10 00:47 UTC, HussainGynai commented on rj_gameplay/stp/role/assignment/naive.py
> +                #     continue
Delete these commented lines

2021-11-10 00:47 UTC, HussainGynai commented on rj_gameplay/tests/stp/role/test_naive_assignment.py
> +<<<<<<< HEAD
This file has a lot merge conflicts, pls fix.

2022-01-07 06:02 UTC, kfu02 commented
superseded by https://github.com/RoboJackets/robocup-software/pull/1811

2022-01-07 06:02 UTC, closed without merging