Role stickiness
RoboJackets/robocup-software pull request #1739
Opened 2021-10-20 00:21 UTC by Yudai-8-om

## Description
Applied role stickiness

## Steps to test
### Test Case 1
1. run sim
2. move robots and the ball around
3. check stickiness of roles

---
try changing the return of wall_tactic's cost by multiplying that sticky factor by 10, behavior change more obvious
-Kevin

2021-10-26 23:37 UTC, kfu02 requested changes
Can you take care of the GH Actions complaints? Other than that it looks like switch_cost is working, so good to merge once the style complaints are in

2021-10-27 01:00 UTC, adithya-gv approved these changes
Seconding Kevin's changes but otherwise looks good!

2021-10-31 23:40 UTC, rkbard requested changes
Fix or clarify the GH action warnings, ex /tactic/wall_tactic.py#L53, or stp/role/assigment/naive.py#L116, etc.

2021-11-02 03:23 UTC, kfu02 approved these changes
couple minor things (one of which fixes style complaint brought up by @rkbard ) but nice work overall!

2021-11-02 03:23 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/wall_tactic.py
> +    # def switch_cost_fn(
you can delete this commented out code

2021-11-02 03:23 UTC, kfu02 commented on rj_gameplay/stp/role/assignment/naive.py
> +                    robot_costs[robot_idx, request_idx] = 1e9
nice fix

2021-11-02 03:23 UTC, kfu02 commented on rj_gameplay/stp/role/assignment/naive.py
> +                    "Got a non-finite cost ({}) for request {} and unassinged robot".format(
```suggestion
                    "Got a non-finite cost ({}) for request {} and unassigned robot {}".format(
```

will fix the style complain about "unused arguments"

2021-11-10 00:30 UTC, rkbard approved these changes

2021-11-17 00:07 UTC, merged