foreach in all plays
RoboJackets/robocup-software pull request #1741
Opened 2021-10-25 01:32 UTC by hdemusg

## Description
Replaced repetitive statements in plays with foreach loops

## Steps to test
Run simulator

Expected result: It should work

2021-11-02 03:02 UTC, kfu02 requested changes
doesn't build, please merge in the latest changes from ros2 that fix this

2021-11-02 03:02 UTC, kfu02 commented on rj_gameplay/rj_gameplay/play/basic122.py
> +            skil_dict.update(role_results[s])
fix this typo please

2021-11-08 01:38 UTC, adithya-gv requested changes
Code compiles and runs. Fix all of the GH Actions errors but otherwise, looks good to me.

2021-11-16 23:02 UTC, anshulm07 requested changes
Looks good to me, but GitHub Actions errors need to be fixed.

2022-01-07 06:02 UTC, kfu02 commented
superseded by https://github.com/RoboJackets/robocup-software/pull/1811

2022-01-07 06:02 UTC, closed without merging