Two robots passing
RoboJackets/robocup-software pull request #1742
Opened 2021-11-02 23:15 UTC by Yudai-8-om

## Description
basic passing

2021-11-30 20:20 UTC, kfu02 requested changes
This is great, way better than what we've had so far. A few things:
 - when I put the ball in the top left and hit start, sim crashes often, giving this error: "[planner_node-7] terminate called after throwing an instance of 'std::invalid_argument'
[planner_node-7]   what():  Cannot splice trajectories a and b, where a.last() != b.first()" No idea what this means. I'm fine with solving this in a later PR.
 - when the pass doesn't crash sim (i.e. ball starts in top right) the receiver often passes it right back to the original passer. This issue should be fixed for this PR. My hypothesis is that the pass tactic doesn't return done because neither robot has captured the ball yet, so it reassigns the new closest robot to the ball as the passer and the old passer as the new receiver and does the pass again.
 - I left a few comments in the files. Most of them are just "please add explanatory comment here". Will make future dev easier.
Nice work, @Yudai-8-om @adithya-gv and @HussainGynai

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/pivot.py
> +        intent.dribbler_speed = float(self.dribble_speed)
is the cast necessary? dribble_speed is already passed in as a float.

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/pivot_kick.py
> +    def tick(self, robot: rc.Robot, world_state: rc.WorldState,
add a comment here that describes the flow (which I believe from reading goes capture -> pivot -> kick?) since the if-else order doesn't match the sequence of actions

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/receive.py
> +        # elif np.linalg.norm(world_state.ball.vel) > RECEIVE_BALL_SPEED_THRESHOLD:
is this intentionally commented out? if it's not being used I would advise deleting the THRESHOLD param

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/settle.py
> +        if world_state.our_robots[self.robot.id].has_ball_sense or (
could you put a comment explaining what this if statement checks? it looks like "if ball sense OR (ball closer to me than passer AND ball is slow)" but that took some time to figure out

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/stp/role/assignment/naive.py
> +                    "Got a non-finite cost ({}) for request {} and unassinged robot"
```suggestion
                    "Got a non-finite cost ({}) for request {} and unassigned robot"
```

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/stp/role/assignment/naive.py
> +                # Cannot be infinte, will break linear_sum_assignment
```suggestion
                # Using 1e9 because float('inf') will break linear_sum_assignment
```

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/pass_tactic.py
> +            return 1e9
it would be nice if we made role assignment auto-cast float('inf') to 1e9 in the role assigner so we didn't have to remember this magic number

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/pass_tactic.py
> +            return 1e9
added as new task to board, dw about it

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/pass_tactic.py
>      def find_potential_receiver(self, world_state: rc.WorldState) -> rc.Robot:
any reason this one is named "find_potential_receiver" and the one below is "find_passer"? (why "potential"?)

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/pass_tactic.py
>      def find_potential_receiver(self, world_state: rc.WorldState) -> rc.Robot:
also, this doesn't have to be fixed for this PR, but these funcs are so similar that they could be one "find min" function that takes in a cost func as a param: https://www.geeksforgeeks.org/passing-function-as-an-argument-in-python/

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/pass_tactic.py
> +        if robot.id != self.passer_robot.id:
isn't this if already covered in line 164 above?

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/pass_tactic.py
> +            goal_to_receiver = np.linalg.norm(robot.pose[0:2] -
add a few comments explaining chunks of below code, e.g. here I would put 
"add to cost for backwards passes (scaled by backpass_punish_weight)"

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/pass_tactic.py
>          # TODO: pick "most open" pass
this TODO is done, right?

2021-11-30 20:20 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/pass_tactic.py
> +            # self.receiver_cost.potential_receiver = receive_result[
delete this commented out code if it's not being used, or leave comment explaining why it should stay

2021-12-01 00:37 UTC, Yudai-8-om commented on rj_gameplay/rj_gameplay/skill/pivot.py
> +        intent.dribbler_speed = float(self.dribble_speed)
I know, it is weird, but I got an error without float for some reason.

2021-12-22 04:07 UTC, kfu02 commented
I think this is a pretty perfect example as to how our gameplay system is unnecessarily over-complicated. See my last commit msg:  
```
implement basic passing

 - buggy bc doesn't end after one pass (aka Receive never ends)
 - implemented as behavior tree and by circumventing RoleAssignment:
 - passer/receiver are picked on first get_requests() call
 - role costs are set to always pick same passer/receiver
 - first, passer is requested
 - when passer finishes PivotKick, receiver is requested
 - receiver then goes to ball (in theory, poorly implemented rn)
 - when receiver gets ball, Tactic should end (again in theory)
```

2023-07-12 02:32 UTC, closed without merging