Fixed kickoff_play.py MyPy Errors
RoboJackets/robocup-software pull request #1802
Opened 2021-12-06 11:34 UTC by gordonm867

I fixed MyPy errors in kickoff_play.py by replacing "RoleResult" with "role.RoleResult", replacing "calculations" with "wall_calculations" to match an existing class, and modifying the specified return types of some methods to match their actual return types.  I can confirm that the kickoff play still runs on my machine with this code and reports no MyPy errors within the kickoff_play.py file, but I had to change the IPlay class to avoid type incompatibility, and I am not sure if that is what I was supposed to do or if that will destroy other things.

2021-12-07 04:32 UTC, kfu02 requested changes
Resolve the two style checks complaining about "line too long". (See Files Changed tab.)

Not your fault because the style checks didn't pop up until I manually clicked run on them (link your account with my.robojackets.org to resolve this, I think). I will review the change to the IPlay class after style is fixed.

2021-12-08 11:21 UTC, gordonm867 commented
> Resolve the two style checks complaining about "line too long". (See Files Changed tab.)
> 
> Not your fault because the style checks didn't pop up until I manually clicked run on them (link your account with my.robojackets.org to resolve this, I think). I will review the change to the IPlay class after style is fixed.

Oh, thanks for letting me know.  I should have resolved those issues.  I also connected my account with my.robojackets.org.

2021-12-16 22:09 UTC, oddlyspookycherry approved these changes
Works well on my end, good job!

2021-12-18 19:06 UTC, kfu02 approved these changes
Nice job!

2021-12-18 19:40 UTC, merged