play/defensive_clear mypy fix
RoboJackets/robocup-software pull request #1803
Opened 2021-12-07 07:42 UTC by oddlyspookycherry

## Description
Fixed mypy typing errors in the file play/defensive_clear.

## Steps to test
Find "Pull request checks / mypy" and click details.

Expected result: There should be no mypy errors for play/defensive_clear

2021-12-07 07:44 UTC, oddlyspookycherry commented on rj_gameplay/rj_gameplay/play/defensive_clear.py
> +    ) -> Tuple[Dict[SkillEntry[Any], List[RoleResult]], Any]:
Function had incorrect return type. Changed.

2021-12-07 16:16 UTC, kfu02 requested changes
Fix the style errors. (Not your fault for not seeing; the checks take a while to run after you submit a PR.) 

Also, is there any more specific type than Any that could fix the return type? In general Any should be avoided because it's basically the same as not giving a type at all.

2021-12-08 04:52 UTC, oddlyspookycherry commented on rj_gameplay/rj_gameplay/play/defensive_clear.py
> +from typing import Dict, List, Tuple
Removed unused imports.

2021-12-08 04:53 UTC, oddlyspookycherry commented on rj_gameplay/rj_gameplay/play/defensive_clear.py
> +    ) -> Tuple[Dict[tactic.SkillEntry, List[role.RoleResult]],
Return type changed to a proper one.

2021-12-14 20:44 UTC, kfu02 approved these changes
Works well on my machine, nice job. One more minor change in the defensive_clear.py file but otherwise LGTM.

2021-12-14 20:44 UTC, kfu02 commented on rj_gameplay/rj_gameplay/play/defensive_clear.py
>          skills = self.two_mark.tick(world_state, role_results[self.two_mark])
```suggestion
        skills += self.two_mark.tick(world_state, role_results[self.two_mark])
```
line 47 inits an empty list of SkillEntries but then this line resets it to the return type of a tactic's tick(), should change to += instead

2021-12-18 19:58 UTC, adithya-gv approved these changes
LGTM!

2022-01-25 17:51 UTC, merged