Added Black Formatter to "make pretty-lines" Command
RoboJackets/robocup-software pull request #1805
Opened 2021-12-29 00:58 UTC by PotentialError

## Description
Added the formatter Black and its associated config file (pyproject.toml)

## Steps to test
1. Make sure black is installed by either running in a terminal `pip install black` or running `make perf `in the repo
2. cd into the repo in a terminal and run `make pretty-lines` 

Expected result: The black formatter should be stylizing all python files excluding files in the external and build folders

2021-12-29 00:59 UTC, PotentialError commented on makefile
> +	@git diff -U0 --no-color $(DIFFBASE) | black .
Modified Makefile's pretty-lines command to run black on all files (excluding one's defined in config file) instead of yapf

2021-12-29 01:02 UTC, PotentialError commented on pyproject.toml
> +'''
Black's version of a config file where files in the folder external and build are excluded from the formatter.

2021-12-29 01:03 UTC, PotentialError commented on util/requirements3.txt
> +black #python checker
Added black as a required library for the robocup-software repository.

2021-12-29 03:26 UTC, kfu02 approved these changes
Looks good! If you could add the requested comment, that'd be great. (Also, one has to run `./util/ubuntu-setup` to get black installed properly, not `make perf` as the description says. Minor detail though.)

2021-12-29 03:26 UTC, kfu02 commented on makefile
Can you add a comment explaining what `make pretty-lines` does? Any reasonable and short explanation is fine.

2021-12-29 03:43 UTC, kfu02 requested changes
Actually, I retract my last approval. When you put Black to work it [fails all of our style checks](https://github.com/RoboJackets/robocup-software/pull/1806) because that tool and flake8 disagree on the max length of lines. Can you resolve this? Pretty sure this will do it: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length

2021-12-30 02:08 UTC, PotentialError commented on makefile
> +# Restyles all C++ (Clang formatter) and Python files (Black formatter) excluding files in the external and build folders
Added comment describing what `make pretty-lines` does.

2021-12-30 02:09 UTC, PotentialError commented on pyproject.toml
> +line-length = 79
Modified the default line-length to 79 to be compatible with flake8

2021-12-31 01:49 UTC, PotentialError commented on pyproject.toml
> +  | ^/build
Added ^/build to exclude all folders beginning with build

2021-12-31 01:49 UTC, PotentialError commented on setup.cfg
> +extend-ignore = E203, E501
Added to make flake8 compatible with black in terms of line-lengths

2022-01-02 04:19 UTC, kfu02 approved these changes
Looks good! Nice work fixing the style errors.

2022-01-02 05:29 UTC, kasohrab approved these changes
looks good to me!

2022-01-02 23:30 UTC, merged