Apply hashable robot
RoboJackets/robocup-software pull request #1820
Opened 2022-01-17 02:29 UTC by Yudai-8-om

## Description
robot hash is used in role assignment

## Steps to test
### Test Case 1
1. Run sim
2. Check used robots that should return hash and assigned robots that should return rc.Robot

2022-01-17 20:44 UTC, kfu02 requested changes
Merge in the base branch again, I made some changes to basic defense play that will be better to test these changes.
(Also set gameplay node to use basic_defense instead of keepaway play.)

EDIT: I created some merge conflicts with my changes, sorry about that. Key difference is I renamed a list called "assigned_robots" to "robots_for_tactic" to be more clear, and also created a "set_assigned_robots" method for Tactics.

2022-01-17 20:44 UTC, kfu02 commented on rj_gameplay/stp/play/__init__.py
> +                    if robot.__hash__() in used_robots:
You should actually be able to just say this. Python will automatically call the hash function you wrote. (Typically all functions that start with __ are not meant to be called directly by the programmer in Python.)
```suggestion
                    if robot in used_robots:
```

2022-01-17 20:44 UTC, kfu02 commented on rj_gameplay/stp/play/__init__.py
> +                used_robots.add(cheapest_robot.__hash__())
see comment above

2022-01-17 20:44 UTC, kfu02 commented on rj_gameplay/stp/play/__init__.py
> +            print(f'used:{used_robots}')
delete these prints when finalized

2022-01-19 00:45 UTC, kfu02 approved these changes
delete the associated TODO, other than that looks good

2022-01-24 01:24 UTC, N8BWert approved these changes
Basic defense runs well.  I did not encounter any issues running the code and everything looks good.

2022-01-26 02:04 UTC, merged