removed max speed file
RoboJackets/robocup-software pull request #1823
Opened 2022-01-19 01:07 UTC by hdemusg

## Description
Removed max speed file. If there's a file where I need to add the max_speed, do let me know. 

## Associated Issue
"remove max kick speed file" on Clickup

## Steps to test
Running the sim

Expected result: It should work normally.

2022-01-19 01:23 UTC, kfu02 requested changes
Did you remove the references to MAX_KICK_SPEED.py in the repo?

2022-01-24 01:42 UTC, kfu02 requested changes

2022-01-24 01:42 UTC, kfu02 commented on rj_gameplay/rj_gameplay/action/kick.py
> -        if self.kick_speed <= MAX_KICK_SPEED:
the kick speed should still be set here, deleting this whole if-else will make all kicks fail. should keep what was in the if block and delete everything else

2022-01-24 01:42 UTC, p-nayak11 approved these changes, later dismissed
All changes seem to make sense according to the PR.

2022-01-31 00:16 UTC, SokhnaDS approved these changes

2023-07-12 02:31 UTC, closed without merging