self.robot is updated in Skill superclass tick method
RoboJackets/robocup-software pull request #1824
Opened 2022-01-19 01:10 UTC by N8BWert

## Description
TODO: make superclass force robot update in tick()
  (do this quietly with self.robot = world_state.our_robots[self.robot.id]
Made the self.robot update in Skill superclass

## Steps to test
### Test Case 1
basically a revamp so nothing should break and everything should run.

Expected result: Nothing bad

2022-01-24 01:25 UTC, gordonm867 approved these changes
The changes all seem to make sense (mostly just calling super().tick() to update the robot position) and do not seem to break the plays.  Good job!

2022-01-26 00:37 UTC, kfu02 requested changes
See comment, I got an error on the new line

2022-01-26 00:37 UTC, kfu02 commented on rj_gameplay/stp/skill/__init__.py
> +        self.robot = world_state.our_robots[self.robot.id]
When running BasicDef, I got an error claiming NoneType has no attr 'id', which suggests self.robot is None on a tick(). I believe the issue is actually that sometimes the init functions for certain skills take in None as their default param (e.g. skill/receive), but I haven't tested that hypothesis. Can you remove that default param and see if that fixes it?

2022-01-31 01:37 UTC, kfu02 approved these changes
Looks good, but can you move that one comment to the superclass? Thanks

2022-01-31 01:37 UTC, kfu02 commented on rj_gameplay/rj_gameplay/skill/capture.py
> +        """
can you move this comment to the superclass

2022-01-31 01:53 UTC, merged