Repr for skills
RoboJackets/robocup-software pull request #1837
Opened 2022-01-26 05:01 UTC by oddlyspookycherry

## Description
Added __repr__() debugging method to all skills. After review delete the calls to __repr__() from role/passer.

## Steps to test
Run the simulation.

Expected result: console output.

2022-01-26 05:11 UTC, oddlyspookycherry commented on rj_gameplay/rj_gameplay/role/passer.py
> +
Remove after review.

2022-01-26 05:11 UTC, oddlyspookycherry commented on rj_gameplay/rj_gameplay/role/passer.py
> +            print(self.pivot_kick_skill)
Remove after review.

2022-01-28 23:18 UTC, kfu02 requested changes
Looks good, just one small thing to clean up before merge!

2022-01-28 23:18 UTC, kfu02 commented on rj_gameplay/rj_gameplay/gameplay_node.py
> +    # play_selector = None
should put back the comment that was here originally (can simply `git checkout` the file from the base branch)

2022-01-31 01:44 UTC, kasohrab approved these changes
looks good to me

2022-02-05 23:26 UTC, merged