cleaned up line tactic for use in penalty plays
RoboJackets/robocup-software pull request #1853
Opened 2022-02-21 03:39 UTC by SokhnaDS

## Description
Cleaned up line tactic so that the robots start on the side of the field for penalty kicks.  

## Steps to test
### Test Case 1
1. run line_up play on sim

Expected result: The robots should start on the side of the field

2022-02-21 04:29 UTC, kfu02 requested changes
Hey, code looks good, but there's a few things to clean up. (See review comments)

2022-02-21 04:29 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/line_tactic.py
> +                (stp.role.cost.PickClosestRobot(pt), dumb_move.DumbMove)
hey, I think the code changed under you while you were working, but the costFn's name is now `PickClosestToPoint` (see `stp/role/cost.py`)

2022-02-21 04:29 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/line_tactic.py
> +from stp.rc import (
fix these style errors by removing unused imports

2022-02-23 00:11 UTC, kfu02 requested changes
The line up play actually launches now, but it shoves all the robots off of the field, have you tested this locally?

2022-02-23 00:11 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/line_tactic.py
> +            (world_state.field.length_m - world_state.field.border_m) / 2,
these seem to be the wrong coordinates, do you get the correct behavior on your end when you run sim?

2022-02-28 00:29 UTC, HussainGynai approved these changes
LTGM

2022-02-28 00:53 UTC, kfu02 requested changes
some light changes

2022-02-28 00:53 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/line_tactic.py
> +            (world_state.field.width_m - world_state.field.border_m) / 2,
can you switch this minus to a plus so the robots stand slightly outside of the field lines?

2022-02-28 00:53 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/line_tactic.py
>          # TODO: make start on side of the field, so this Tactic is actually useful during penalty situations
you can delete this TODO also

2022-03-02 02:19 UTC, CK-Christopher approved these changes
Everything looks good!

2022-03-16 06:40 UTC, merged