update rj_gameplay/README.md
RoboJackets/robocup-software pull request #1863
Opened 2022-02-28 03:45 UTC by kfu02

## Description
Updated to reflect new SRTP structure.

2022-04-03 23:58 UTC, kasohrab requested changes
these should be updated based on my latest pr

2022-04-03 23:58 UTC, kasohrab commented on rj_gameplay/README.md
> +Coordinates all robots on the field for a given situation. Gets role requests from its tactics, then assigns them according to the cost functions of those role requests. (Examples: Basic122, Basic De
```suggestion
Coordinates all robots on the field for a given situation. Gets role requests from its tactics, then assigns them according to the cost functions of those role requests. (Examples: Basic Offense, Basic Defense)
```

2022-04-03 23:58 UTC, kasohrab commented on rj_gameplay/README.md
> +GameplayNode -> SituationAnalyzer -> Play (selected based on situation) -> Tactic(s) -> Role(s) -> Skill(s)
```suggestion
GameplayNode -> Play Analysis/Selector -> Play (selected based on situation) -> Tactic(s) -> Role(s) -> Skill(s)
```

2022-04-03 23:59 UTC, parkerra commented on rj_gameplay/README.md
> +The general flow of how a RobotIntent (or specific command for the robot) is created is as follows:
```suggestion
The general flow of how a RobotIntent (or specific command for the robot) is created as follows:
```

2022-04-03 23:59 UTC, kasohrab requested changes
and this

2022-04-03 23:59 UTC, kasohrab commented on rj_gameplay/README.md
>  Uses SituationAnalyzer to select the best play to run, calling tick() on the
```suggestion
Uses basic_play_selector to select the best play to run, calling tick() on the
```

2022-04-04 00:01 UTC, kasohrab approved these changes
looks good to me

2022-04-04 00:02 UTC, parkerra approved these changes

2022-04-04 00:19 UTC, merged