Penalty offense prep
RoboJackets/robocup-software pull request #1872
Opened 2022-03-14 01:04 UTC by Yudai-8-om

## Description
The striker will be positioned at .5m behind from the ball as a prep.
Line tactics are commented out until they are ready to use

## Steps to test
### Test Case 1
1. Run sim
2. check the striker's position

2022-03-16 00:28 UTC, CK-Christopher reviewed
In basic_seek, it crashes unless stp.role.cost is imported. I am not sure why though. I might just be my VM. In the future, the commented out line tactic needs to match its method header. Other than that, it looks good to me.

2022-03-16 00:44 UTC, CK-Christopher approved these changes

2022-03-29 23:52 UTC, kfu02 requested changes
some small suggestions, overall behaves well

2022-03-29 23:52 UTC, kfu02 commented on rj_gameplay/rj_gameplay/gameplay_node.py
Can you avoid committing to gameplay_node in this PR? You can reset this file to what's in ros2 with https://stackoverflow.com/questions/2364147/how-to-get-just-one-file-from-another-branch

2022-03-29 23:52 UTC, kfu02 commented on rj_gameplay/rj_gameplay/play/penalty_offense.py
> +                # assume line tactic is working
can you put the working line tactic in after #1874 is merged?

2022-03-29 23:52 UTC, kfu02 commented on rj_gameplay/rj_gameplay/play/penalty_offense.py
> +            self._state = State.PREP
you should add a while loop here that checks if the number of requested tactics is actually assigned before switching the state, see this line:

https://github.com/RoboJackets/robocup-software/pull/1855/files#diff-a0f92563cb784149768f1724a5d7e152b2ce3b8042d3477f11ce84f823ddb589R111

2022-03-29 23:52 UTC, kfu02 commented on rj_gameplay/rj_gameplay/play/penalty_offense.py
> +                # assume line tactic is working
(this can be done after merging this PR if necessary)

2022-03-30 00:01 UTC, p-nayak11 approved these changes
All of the robots behaved in the proper manner and the striker appropriately approaches the ball in the offensive penalty situation.

2022-05-02 19:41 UTC, kfu02 commented
was used in #1887 , will be cleaned up by #1894 but I'm merging current state in now to give credit to @CK-Christopher

2022-05-02 19:52 UTC, merged