50/50
RoboJackets/robocup-software pull request #1878
Opened 2022-03-30 00:32 UTC by N8BWert

## Description
The ball handler tactic randomly assigns a robot to either pass or shoot (equal probability).

## Steps to test
### Test Case 1
1. Run Keepaway
2. Observe the robots passing and shooting
3. Profit

Expected result: The robots should pass and shoot

2022-03-30 00:58 UTC, SokhnaDS reviewed
In most cases it works; however, there are some cases in which there is a robot from our team blocking the pass in between two other robots. Then, none of the robots can do anything else. probably should be addressed.

2022-04-03 23:46 UTC, HussainGynai requested changes
Your logic looks mostly good, although your description says it should try to pass or shoot probabilistically, but it just passes if there is no good shot. Also the tactic currently crashes as soon as the ball handler captures the ball. Also delete debug prints when done with them.

2022-04-03 23:46 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/ball_handler_tactic.py
> +CUTOFF_ANGLE = math.cos(math.pi / 10)
This isn't an angle, its the cosine of an angle

2022-04-03 23:46 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/ball_handler_tactic.py
> +            # TODO: these lines are a little ugly, any fix?
What does this mean?

2022-04-03 23:46 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/ball_handler_tactic.py
> +                print("SHOOOOOOOOOOOOOTTTTTTING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
Get rid of debug print

2022-04-03 23:46 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/ball_handler_tactic.py
> +            print('init shoot')
Delete debug print

2022-04-03 23:46 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/ball_handler_tactic.py
> +            best_shot = striker.StrikerRole()._find_target_point(world_state = world_state, kick_speed = 4.0)
This line errors and causes sim to crash.

2022-04-03 23:46 UTC, HussainGynai commented on rj_gameplay/rj_gameplay/tactic/ball_handler_tactic.py
> +                        self._state = State.INIT_PASS
I thought it should pass or shoot probabilistically, this logic is just that if there is not a good shot, then pass. This is fine, but just not what was written in the description of the tactic.

2022-04-03 23:52 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/ball_handler_tactic.py
> +            # TODO: these lines are a little ugly, any fix?
that's my TODO
you can delete it

2022-10-31 20:33 UTC, closed without merging