Formations Class
RoboJackets/robocup-software pull request #1880
Opened 2022-04-03 18:34 UTC by p-nayak11

## Description
A formations class to divide the field into different regions for the seekers to go to. The current formation that is in the class is the X formation with 2 seekers up front, 1 seeker in the middle, and seekers in the back. The tactic only calls three seekers so the first two regions are being occupied. I will create the new diamond formation and commit to this branch.

## Steps to test
### Test Case 1
1. Run sim to make sure nothing crashes

Expected result: Three robots should move after ball is moved.

2022-04-04 00:05 UTC, HussainGynai approved these changes
LGTM!

2022-04-04 00:05 UTC, HussainGynai commented on .pre-commit-config.yaml
>      name: isort (python)
I don't think you meant to push changes to this file.

2022-04-04 00:27 UTC, p-nayak11 commented on .pre-commit-config.yaml
>      name: isort (python)
Not sure where the change came from

2022-04-04 01:32 UTC, kfu02 requested changes
Requesting some Formation class design changes that we discussed IRL.

2022-04-04 01:32 UTC, kfu02 commented on .pre-commit-config.yaml
>      name: isort (python)
^ everyone has to commit this change, otherwise precommit won't let them commit

2022-04-04 01:32 UTC, kfu02 commented on rj_gameplay/stp/rc.py
> +        Conveniance function for getting our goal post coordinates
```suggestion
        Convenience function for getting our goal post coordinates.
```

2022-04-04 01:32 UTC, kfu02 commented on rj_gameplay/stp/rc.py
> +        Conveniance function for getting their goal post coordinates
```suggestion
        Convenience function for getting their goal post coordinates.
```

2022-04-04 01:32 UTC, kfu02 commented on rj_gameplay/stp/rc.py
> +        Conveniance function for getting our goal post coordinates
also could you add a nice return: here like below?

2022-04-04 01:32 UTC, kfu02 commented on rj_gameplay/stp/utils/formations.py
> +        Conveniance function for getting center of a region
```suggestion
        Convenience function for getting center of a region.
```

2022-04-04 01:32 UTC, kfu02 commented on rj_gameplay/rj_gameplay/tactic/basic_seek.py
> +        self, world_state: stp.rc.WorldState, num_seekers: int, formations: List
should pass in your new Formations class here

2022-04-04 01:32 UTC, kfu02 commented on rj_gameplay/stp/utils/formations.py
> +class Formations:
this is written a bit like a static method, should have types of Formations subclass some abstract Formation class and pass that in instead

2022-04-06 19:12 UTC, kfu02 requested changes
Hey, this looks much cleaner than before, nice work. I left a few suggestions for how to name things that I believe should be done, but talk to me if you disagree; none of them affect the functionality or design. After we hash those out I can approve this.

In the future we should account for blocking our own seekers somehow, but that's a different PR. (See robot 5 blocking robot 3 below.)

![Screenshot from 2022-04-06 15-03-08](https://user-images.githubusercontent.com/30275369/162050781-6815f2ff-31a0-4677-8f4e-8f4c06c94bd4.png)

2022-04-06 19:12 UTC, kfu02 commented on rj_gameplay/stp/formations/diamond_formation.py
> +class Diamond_formation(stp.formations.Formations):
```suggestion
class DiamondFormation(stp.formations.Formations):
```

nit: this is how the rest of our codebase's Python classes are styled, would be nice to match (if you do this don't forget to change the references to this class)

2022-04-06 19:12 UTC, kfu02 commented on rj_gameplay/stp/formations/diamond_formation.py
> +    def get_centroid(self) -> List:
```suggestion
    def get_centroids(self) -> List:
```

since it returns multiple centroids

2022-04-06 19:12 UTC, kfu02 commented on rj_gameplay/stp/formations/diamond_formation.py
> +    def get_centroid(self) -> List:
(again don't forget to change references above)

2022-04-06 19:12 UTC, kfu02 commented on rj_gameplay/stp/formations/__init__.py
> +    def get_centroid(self) -> List:
```suggestion
    def get_centroids(self) -> List:
```

since it returns multiple centroids

2022-04-06 19:12 UTC, kfu02 commented on rj_gameplay/stp/formations/x_formation.py
> +class X_formation(stp.formations.Formations):
```suggestion
class XFormation(stp.formations.Formations):
```

same nit as above with Diamond_formation vs DiamondFormation

2022-04-07 22:01 UTC, p-nayak11 commented
> Hey, this looks much cleaner than before, nice work. I left a few suggestions for how to name things that I believe should be done, but talk to me if you disagree; none of them affect the functionality or design. After we hash those out I can approve this.
> 
> In the future we should account for blocking our own seekers somehow, but that's a different PR. (See robot 5 blocking robot 3 below.)
> 
> ![Screenshot from 2022-04-06 15-03-08](https://user-images.githubusercontent.com/30275369/162050781-6815f2ff-31a0-4677-8f4e-8f4c06c94bd4.png)

I saw this earlier. I will work on it later.

2022-04-13 00:19 UTC, kfu02 approved these changes
LGTM

2022-04-13 00:48 UTC, merged