fix ubuntu-setup by moving git installs out
RoboJackets/robocup-software pull request #1898
Opened 2022-05-21 00:44 UTC by kfu02

## Description
When installing our repo on a new machine, I realized why we had to git submodule update manually before after running ./util/ubuntu-setup. Turns out git stopped allowing their installs (including pre-commit) to be done by sudo. This PR fixes that by making a new util install script.

TODO: change docs in #1897 to account for this, if merged.

2022-06-06 21:33 UTC, kasohrab requested changes
looks good! just one small change, so that people can run the git setup script more than once without it failing (if they want to update submodules later down the line using the same script).

2022-06-06 21:33 UTC, kasohrab commented on util/git-setup
> +pre-commit autoupdate
```suggestion
# install pre-commit hooks if not already installed
if ! command -v pre-commit &> /dev/null
then
	echo "-- Installing pre-commit hook"
	pre-commit install
	pre-commit autoupdate
fi
```

2022-06-07 02:42 UTC, kfu02 commented on util/git-setup
> +pre-commit autoupdate
fancy

2022-06-07 03:18 UTC, kasohrab approved these changes

2022-06-07 20:50 UTC, merged