Delete outdated files
RoboJackets/robocup-software pull request #1918
Opened 2022-07-03 04:34 UTC by kasohrab

## Description
Title.

## Associated / Resolved Issue
Resolves [ClickUp card](https://app.clickup.com/t/2jmad9y)

## Steps to test
### Test Case 1
1. make clean && make perf
2. run sim
3. no regressions

## Key Files to Review
basically just check if we need anyone of them still (I doubt it) or if there's anything else I should delete.
## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

**Expected result:** works

2022-07-03 04:43 UTC, kasohrab commented on autoupdate-docs.sh
> -make apidocs
we used to host docs on the gh-pages branch

2022-07-03 04:43 UTC, kasohrab commented on cmake/MbedTargets.cmake
> -# ***** DO NOT MANUALLY EDIT THIS FILE *****
robot previously used mbed as MCU.

2022-07-03 04:43 UTC, kasohrab commented on cmake/MbedUtil.cmake
> -function(MBED_SET_PLATFORM target_var_base)
firmware and software used to be a monorepo

2022-07-03 04:43 UTC, kasohrab commented on robocup.sublime-project
> -{
people liked sublime

2022-07-03 04:43 UTC, kasohrab commented on runcomp.sh
> -if ! command -v git >/dev/null; then
from before ros2, custom launch script

2022-07-03 04:43 UTC, kasohrab commented on util/arch-setup
> -echo "-- Installing grSim default configuration"
people liked arch

2022-07-03 04:43 UTC, kasohrab commented on util/osx-setup
> -if [ ! $(which brew) ]; then
before ros2 we could support osx.

2022-07-03 04:43 UTC, kasohrab commented on util/profile
> -# We have this mess because there is no way to get the PID
no idea lol

2022-07-03 04:43 UTC, kasohrab commented on cmake/FindBullet.cmake
> -# - Try to find the Bullet physics engine
we used to have our own simulator, then we switched to grSim (now we use erforce's sim). Our 2012 and 2013 [tdps](https://wiki.robojackets.org/Team_Description_Papers) talk about it a good bit

2022-07-03 23:55 UTC, p-nayak11 requested changes
All of the deletions make sense. I believe the rj_gameplay/tests folder is something that should be considered for scrapping as well since we don't use it at all (unless it has a purpose?).

2022-07-03 23:55 UTC, p-nayak11 commented on soccer/CMakeLists.txt
> -find_package(libusb-1.0 REQUIRED)
I assume that we don't need to communicate with a USB anymore?

2022-07-05 01:03 UTC, kasohrab commented
> All of the deletions make sense. I believe the rj_gameplay/tests folder is something that should be considered for scrapping as well since we don't use it at all (unless it has a purpose?).

I deleted all the tests that are outdated, the test-rc.py is still useful. I'm not sure if our CI actually runs that test right now 😅, but still it's a good regression test to have. We can always design a good testing framework later, so I see no issue with deleting the outdated stuff right now.

2022-07-05 01:04 UTC, kasohrab commented on soccer/CMakeLists.txt
> -set(FOUND_A_BOOST_PYTHON FALSE)
we use ros2 now, and no longer need boost python

2022-07-05 22:33 UTC, p-nayak11 approved these changes
LGTM!

2022-07-05 23:00 UTC, kfu02 approved these changes
can't believe we used to have firmware sounds

2022-07-06 00:05 UTC, merged