Christian engman/robocup sw tutorial
RoboJackets/robocup-software pull request #1955
Opened 2022-10-24 00:33 UTC by cengman2017

Pull request for software tutorial

Tutorial Step 2 (4 Wallers):
![robocup-tutorial-4-wallers](https://user-images.githubusercontent.com/85267499/197426128-afde92dd-88c0-4601-b193-ad99bf94ee5c.png)

Tutorial Step 4:
/gameplay/robot_intent/robot_0 uses messages type at:
/home/cxe6789/RoboCupTutorial/robocup-software/rj_msgs/msg/RobotIntent.msg

Tutorial Step 5:
gameplay/robot_intent/robot_0 is published to by /gameplay_node, and is subscribed to by /planner and /control

2022-11-07 01:10 UTC, cengman2017 commented
![robocup_tutorial-bananas](https://user-images.githubusercontent.com/85267499/200206918-4cb1f69f-42a0-4286-a8a5-57395d864905.png)
![robocup_tutorial-blueberries](https://user-images.githubusercontent.com/85267499/200206921-d630808a-76d2-4d58-ae11-b52e623b23c3.png)
/team_fruit shows proper fruit for both colors

2022-11-07 01:22 UTC, p-nayak11 requested changes
There are currently a lot of style errors! Run make pretty-line before you commit.

2022-11-09 00:31 UTC, p-nayak11 approved these changes
It looks good! Good job on finishing the tutorial!

2022-11-09 00:31 UTC, p-nayak11 commented on .vscode/settings.json
> +    "ros.distro": "foxy"
Make sure these vscode configs are local to your machine, and that they aren't pushed to the main branch!

2022-11-09 00:31 UTC, p-nayak11 commented on soccer/src/soccer/soccer-mom/soccer_mom.cpp
> +    publisher_ = this->create_publisher<std_msgs::msg::String>("/team_fruit", rclcpp::QoS(1));
In future projects, make sure to adhere to C++ doc string formats. It will be enforced later on! These specifications can be found in the Contributions page of our documentation.

2022-11-09 00:31 UTC, p-nayak11 commented on soccer/src/soccer/soccer-mom/soccer_mom.hpp
> +
Same as above

2022-11-09 00:31 UTC, p-nayak11 commented on soccer/src/soccer/soccer-mom/soccer_mom_node_main.cpp
> +
Same as above

2022-11-09 00:32 UTC, p-nayak11 commented
Finished the tutorial!

2022-11-09 00:32 UTC, closed without merging