Daniel wu/robocup sw tutorial
RoboJackets/robocup-software pull request #1963
Opened 2022-11-07 01:33 UTC by dwu359

<img width="1265" alt="Screen Shot 2022-11-06 at 8 24 53 PM" src="https://user-images.githubusercontent.com/54150946/200208269-3e473f21-5b4d-4580-8c96-62493fbf6ffc.png">
<img width="1265" alt="Screen Shot 2022-11-06 at 8 25 24 PM" src="https://user-images.githubusercontent.com/54150946/200208271-99c40d3f-a6b1-4448-986a-df804dcf3811.png">

Stuff that confused me in this tutorial: Could be more clear on what Roles, Tactics, and Plays are in step 3, could also be more clear on what launch files/parts of the cmake files that should be modified for step 6

2022-11-09 00:25 UTC, p-nayak11 requested changes
It looks good so far! Good job on completing steps 3, 5, and 6. Please add step 4 in this PR as well.

2022-11-09 00:25 UTC, p-nayak11 commented on .vscode/c_cpp_properties.json
> +}
Make sure that the changes that you make for your vscode configs are not pushed to the main branch.

2022-11-09 00:25 UTC, p-nayak11 commented on .vscode/settings.json
> +}
Same as above.

2022-11-09 00:25 UTC, p-nayak11 commented on rj_gameplay/rj_gameplay/role/runner_role.py
> +    def tick(self, world_state: stp.rc.WorldState) -> RobotIntent:
When creating new projects in the future, please adhere to the doc strings for the language.

2022-11-09 00:25 UTC, p-nayak11 commented on soccer/src/soccer/soccer_mom.cpp
> +
Same comment as above. It is extremely important on the C++ aspect of the code base as we don't have too much documentation on it the first place.

2022-11-09 03:10 UTC, dwu359 commented
> It looks good so far! Good job on completing steps 3, 5, and 6. Please add step 4 in this PR as well.

For step 4, the file is /rj_msgs/msg/RobotIntent.msg

2022-11-14 00:25 UTC, p-nayak11 approved these changes
LGTM

2022-11-14 00:33 UTC, closed without merging