Planner ball obstacle
RoboJackets/robocup-software pull request #1983
Opened 2022-12-07 00:37 UTC by sid-parikh

## Description

This PR updates the planning system to consider the ball a dynamic obstacle, and plan paths that keep a certain distance away from the ball as published by the coach node

## Associated / Resolved Issue
Resolves [make planner respect ball on stop](https://app.clickup.com/t/34c4duz)

## Design Documents
[Link](link-to-design-doc)

## Steps to Test
### Test Case 1
1. Run the sim (green check/normal mode). Currently, six robots move in a predefined manner. Robot 1 (the defender) is the only one set to pay any attention to the ball. 
2. Place the ball in/near the path of robot 1
3. Give the ball some velocity in a collision course with robot 1's path

**Expected result:** Robot 1 avoids touching the ball

### Test Case 2: STOP
1. Run the sim in STOP. (Coach node should be publishing a min_dist_from_ball at 0.5)
2. Place the ball in/near the path of robot 1
4. Give the ball some velocity in a collision course with robot 1's path

**Expected result:** Robot 1 should keep a larger radius (0.5 in some unit?) around the ball.

## Key Files to Review
Plan Request: struct changed to keep a `min_dist_from_ball` field. also changed `fill_obstacles` (utility called by planners) to use the field.
 * `plan_request.hpp`
 * `plan_request.cpp`

Planner Node: now maintains a `coach_state` subscription and inserts the `min_dist_from_ball` data into each plan request when creating them from RobotIntents.
 * `planner_node.hpp`
 * `planner_node.cpp`

## Review Checklist

- [x] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [x] **Remove extra print statements**: Any print statements used for debugging should be removed
- [x] **Tag reviewers**: Tag some people for review and ping them on Slack

2022-12-07 23:44 UTC, kfu02 requested changes
This is a really good PR, @sid-parikh ! I just have one small request: can you reenable drawing the circle around the ball? (I provided an example in PR comment)

(also, can you enable for all robots instead of just robot 1?)

2022-12-07 23:44 UTC, kfu02 commented on soccer/src/soccer/planning/planner_node.hpp
> +        auto lock = std::lock_guard(mutex_);
nice

2022-12-07 23:44 UTC, kfu02 commented on soccer/src/soccer/planning/planner/plan_request.cpp
> +        out_dynamic->emplace_back(kBallRadius + in.min_dist_from_ball, out_ball_trajectory);
can you add a call to the debug drawer here that draws a red circle around the ball when min_dist>0? (like you saw the old system do)

here is an example: https://github.com/RoboJackets/robocup-software/blob/726fba6e4c6559b93704d28368d73f26d7adc9e9/soccer/src/soccer/planning/planner/path_target_planner.cpp#L41

2022-12-08 00:24 UTC, kfu02 commented
Oh, to answer your question about units: everything is in meters. So our robots are 0.09 meters in radius, the STOP dist is 0.5 m, etc.

2023-01-16 01:41 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/plan_request.cpp
> +        out_dynamic->emplace_back(kBallRadius + in.min_dist_from_ball, out_ball_trajectory);
Added in the latest commit. Should be visible in all previously described tests. I wanted to do this earlier, but couldn't figure it out. Thanks for helping!

2023-01-23 01:38 UTC, kasohrab approved these changes
LGTM

2023-01-23 01:47 UTC, merged