Blockers
RoboJackets/robocup-software pull request #2007
Opened 2023-02-22 00:27 UTC by dwu359

## Description
This is a defense strategy to move in between the ball and the goal to block anyone from shooting the ball into the goal.

## Associated / Resolved Issue
Resolves [ClickUp card](https://app.clickup.com/t/86777u61x)

## Steps to Test
### Test Case 1
1. make run-sim
2. place a ball somewhere on the same side as the defenders' goal. 
**Expected result:**
Defender robots should move in between the ball and the goal.

## Key Files to Review
Group 1
 * defense.cpp
 * defense.hpp
 * blockers.cpp
 * blockers.hpp

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1
- [ ] Step 2

2023-02-22 18:19 UTC, kfu02 requested changes
hey Daniel, can you run `make pretty-lines` to fix the style errors?

also, let's wait on Amogh's PR (#1996 ) so you can use that interface, work with him to ensure your role will work with it

2023-03-09 03:33 UTC, kfu02 requested changes
hey Daniel, can you fix all the check warnings? also, see my comment about making the marker work between any two points (also let's rename Blocker to Marker)

2023-03-09 03:33 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/blocker.cpp
> +    constexpr bool ignore_ball = false;
should be IGNORE_BALL

2023-03-09 03:33 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/blocker.cpp
> +        (world_state->ball.position - goal_center) * factor + goal_center,
so right now it looks like the blocker has to block between the goal and the ball, which is the same behavior as the waller. can you change this to block between any two arbitrary points (e.g. two robots' positions)?

2023-03-15 18:00 UTC, kfu02 reviewed
can you resolve the merge conflicts with ros2? I think they come from your recent changes in #2015

2023-03-29 02:26 UTC, kfu02 requested changes
hey Daniel, you have a few check warning complaints to fix, shouldn't take too long. (google it if any are confusing, these are pretty common warnings.) nice work so far!

2023-04-05 17:47 UTC, kfu02 requested changes
hey Daniel, the behavior looks pretty good! I will say the one thing missing is that when the ball is kicked at the marker, the marker will back up rather than stay in place to steal the ball. can you add a bit of logic to say "if the ball is being kicked in my vicinity, go try to intercept it?" the latest passing PR #2037 should help with that

2023-04-05 17:47 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/marker.cpp
> +    intent.motion_command = planning::PathTargetMotionCommand{goal, face_option, IGNORE_BALL};
merge in ros2. thanks to the changes in #2020 , this should be much easier to work with now. see[ these changes](https://github.com/RoboJackets/robocup-software/pull/2020/files#diff-ca908df5b2761a194bedc670ac10709d077ac28b53ec7d8a0abeb8596d775380R38) in particular

2023-07-12 02:19 UTC, sid-parikh commented
Working wallers code can be found in comp 23 branches.

2023-07-12 02:19 UTC, closed without merging