do what chatgpt said
RoboJackets/robocup-software pull request #2023
Opened 2023-03-27 02:58 UTC by kfu02

## Description
Describe your pull request.

## Associated / Resolved Issue
Resolves # or [ClickUp card](link-to-clickup-card)

## Design Documents
[Link](link-to-design-doc)

## Steps to Test
### Test Case 1
1. Step 1
2. Step 2
3. Step 3

**Expected result:**???

## Key Files to Review
Group 1
 * File 1
 * File 2

Group 2
 * File 3
 * File 4

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1
- [ ] Step 2

2023-03-27 04:03 UTC, kasohrab requested changes
You can delete the todo. Basically since it takes more than one cpu cycle it could be race condition. cpp is not a high enough level language to abstract the need for locking away (like python has for the most part)

2023-03-27 04:03 UTC, kasohrab commented on soccer/src/soccer/planning/planner_node.hpp
>          return last_play_state_;
Yes it should have be locked: https://preshing.com/20130618/atomic-vs-non-atomic-operations/.

2023-03-27 04:04 UTC, kasohrab commented
Also the rest looks great! We should port it to firmware.

2023-03-27 04:05 UTC, kasohrab commented
Oh I realize that todo was also for testing lol

2023-03-27 05:17 UTC, kfu02 commented
> Oh I realize that todo was also for testing lol

yes lol but it was a genuine question I had too, so thanks!

2023-03-27 05:31 UTC, kfu02 commented
> Also the rest looks great! We should port it to firmware.

not quite, it still doesn't run when the bot does [auto-style](https://github.com/RoboJackets/robocup-software/pull/2023/commits/f091df4cce047bfd225b005001597aae1297781c), let me work on that

2023-03-28 23:41 UTC, N8BWert approved these changes
worked for me

2023-03-28 23:53 UTC, dwu359 commented
Works

2023-03-28 23:53 UTC, dwu359 approved these changes

2023-03-29 01:14 UTC, kasohrab approved these changes
Lgtm

2023-03-29 01:16 UTC, merged