Lineup
RoboJackets/robocup-software pull request #2057
Opened 2023-04-12 00:31 UTC by jacksherling

## Description
Adds lineup position, either 

## Associated / Resolved Issue
Resolves [ClickUp card](https://app.clickup.com/t/8677t9bb5)

## Steps to Test
### Test Case 1
1. Use penaltylineup or sidelineup enum values and view result in sim

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

2023-04-19 06:04 UTC, kfu02 requested changes
Hey @jacksherling , there are some style fixes and minor things to clean up, could you handle that by next Tuesday?

2023-04-19 06:04 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/their_side_lineup.cpp
> +    // double x = field_dimensions_.our_right_corner().x(); // IF OTHER SIDE
delete

2023-04-19 06:04 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/their_side_lineup.hpp
> + * Vertical line on our side
```suggestion
 * Vertical line on their side
```

2023-04-19 06:04 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/their_side_lineup.hpp
> +    bool init_ball_pos_valid_{false};
delete

2023-04-19 06:04 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/their_side_lineup.hpp
> +    int r_id_{};
figure out how to use Position superclass's r_id_ (it has this field already)

2023-09-11 03:08 UTC, sid-parikh commented
See comp fork for a working version of this (if it isn't already in ros2)

2023-09-11 03:08 UTC, closed without merging