Shoot only
RoboJackets/robocup-software pull request #2063
Opened 2023-04-12 14:14 UTC by N8BWert

## Description
This PR outlines the basics of a shoot only offense.  In this offense strategy, one robot (the closest to the ball that is playing offense) will attempt to obtain the ball and shoot the ball at the opponents goal.

EDIT: PR #2069 was merged into this branch. It adds a pivot step before any shot on goal to improve line kick consistency, but only does so at the Position level, which is not ideal (should be a planner, but planners are hard to compose).

## Associated / Resolved Issue
[coordinate shoot-only offense](https://app.clickup.com/t/8677u14px)

## Steps to Test
### Test Case 1
1. make perf && make run-sim
2. assign any number of robots to offense
3. click start (the robots will reassign is switched to offense and closer to the ball while sim is playing if you want to see that just start then assign robots to offense)

**Expected result:**The robot closest to the ball should get the ball and shoot it into the net.  Currently the robot keeps doing this on loop which may be undesired, but I would assume the coach will reassign him so I have the scorer on loop.

## Key Files to Review
Messages
 * rj_msgs/request/ScorerRequest.msg
 * rj_msgs/response/ScorerResponse.msg
 * soccer/src/soccer/strategy/agent/communication.*pp

Offense
 * soccer/src/soccer/strategy/agent/position/offense.*pp

## Review Checklist

- [X] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [X] **Remove extra print statements**: Any print statements used for debugging should be removed
- [X] **Tag reviewers**: Tag some people for review and ping them on Slack

2023-04-16 01:58 UTC, kfu02 requested changes
This is looking good so far, but is there a way to reset which robot is the scorer after a shot is taken? Right now the looping behavior will probably net us double touch fouls. I imagine it would be something like once the scorer has attempted a kick, send a broadcast message that resets the value of scorer for every Offense player.

2023-04-16 01:58 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/offense.cpp
> +            // The collect planner check_is_done() is wonky so I added a second clause to check
is there a way to fix that planner's is_done? (e.g. just add the second clause into that is_done directly)

2023-04-16 01:58 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/offense.cpp
> +void Offense::handle_scorer_response(std::vector<communication::AgentResponseVariant> responses) {
check warning

2023-04-16 01:58 UTC, kfu02 commented on soccer/src/soccer/strategy/agent/position/offense.hpp
> +    bool scorer = false;
```suggestion
    bool scorer_ = false;
```
(will require changes everywhere else in .cpp)

2023-04-21 19:34 UTC, Sdssourcing commented
#

2023-04-26 00:44 UTC, merged