Remove coach node
RoboJackets/robocup-software pull request #2101
Opened 2023-09-27 00:10 UTC by Ninjatest321

This pull request adds a Referee PlayState subscription to all the files that use CoachState and don't have play state already (which is just Agent Action Client). This is part of the plan to remove CoachNode.

2023-09-28 14:51 UTC, sid-parikh requested changes

2023-09-28 14:51 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/agent_action_client.cpp
> +    return;
Hey amogh, can you also change the AC & Position to get play state data from this topic? the callback is empty right now; we should be forwarding it to position. I know position doesn't use play state data right now, but that's okay

2023-10-16 00:48 UTC, sid-parikh approved these changes
Looks good, thanks!

2023-10-18 00:10 UTC, Ninjatest321 commented
This last commit calculates global overrides in the Planner Node (planner_node.cpp)

2023-11-06 01:40 UTC, p-nayak11 commented
Look at PR #2131

2023-11-06 01:40 UTC, closed without merging