Speed Calculation in Sim
RoboJackets/robocup-software pull request #2153
Opened 2023-12-04 01:40 UTC by Squid5678

## Description
James and I (Aalind) were assigned a task to calculate the speed necessary to pass in sim. We used the Technical Description Paper from Tigers Mannheim in order to find an accurate formula to use. We also created constants that will need to be tuned. As of right now, the values are tuned for the simulator.

## Associated / Resolved Issue
Resolves https://app.clickup.com/2209401/v/l/li/900501233982

## Design Documents
N/A

## Steps to Test
Works as expected in sim when run. Further testing needs to be done on an actual robot.

**Expected result:**
Passing works as expected (with speed changing based on distance).

## Key Files to Review
Offense
 * offense.cpp
 * offense.hpp

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1
- [ ] Step 2

2024-01-11 21:01 UTC, sid-parikh requested changes
Good work! Just a couple nits.

2024-01-11 21:01 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/offense.cpp
> +        //this->target_robot_id = 2;
please remove debug statements like this before submitting a PR. this is trivial enough to add back in later

2024-01-11 21:01 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/offense.hpp
> +    const float FINAL_BALL_SPEED {0.0f};
make these two constants `static constexpr` instead of just `const`

2024-01-11 21:01 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/offense.hpp
> +    float dist {0.0f};
i'm not convinced that `dist` needs to be a member. can we keep it local to the `state_to_task` function?

2024-01-15 01:02 UTC, Squid5678 commented
@sid-parikh made the changes as requested.

2024-01-23 17:14 UTC, sid-parikh requested changes
This is great! Sorry, a couple more things I didn't notice on the first review.

2024-01-23 17:14 UTC, sid-parikh commented on framework
hey, we can't commit this. make sure to move this directory outside of `robocup-software`

2024-01-23 17:14 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/offense.hpp
> +    static constexpr float FINAL_BALL_SPEED{0.0f};
can we change these constants style to `kFinalBallSpeed` and `kBallDecel` ? also leave a comment explaining they are included here for the sake of kick speed calculation. also, I think we already have a constant related to ball deceleration. check if it's the same or not

2024-01-23 17:14 UTC, sid-parikh commented
quick tip: push the "re-request review" button on my name after you make changes so I'll see it again.

2024-01-29 22:25 UTC, sid-parikh approved these changes
Looks good! Feel free to press merge whenever.

2024-01-31 00:17 UTC, merged