Position fsm
RoboJackets/robocup-software pull request #2173
Opened 2024-01-29 00:49 UTC by rishiso

## Description
Implements position management automatically based on states of the game. Positions used to be static (3 defense, 2 offense, 1 goalie), but now they change dynamically.

## Associated / Resolved Issue
[ClickUp card](https://app.clickup.com/t/86aypjcg3)

## Steps to Test
Run in sim and move the ball to different halves. The positions of robots should change dynamically.

## Key Files to Review
 * robot_factory_postion.cpp

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

2024-01-29 21:45 UTC, sid-parikh requested changes

2024-01-29 21:45 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/robot_factory_position.cpp
> +    if (robot_id_ == 0) {
you can't assume 0 is the robot id. you need to get that information from the referee. If i'm not mistaken, there is already a mechanism for AAC to pass this information to its Position. if not, let's figure out how to add it.

2024-01-29 21:45 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/robot_factory_position.cpp
> +    typedef struct std::pair<int, double> RobotPos;  // (robotId, yPosition)
```suggestion
    using RobotPos = std::pair<int, double>;  // (robotId, yPosition)
```
note the GH Action warning here. just simpler syntax it's completely equivalent

2024-01-29 21:45 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/robot_factory_position.cpp
> +    for (int i = 0; i <= 5; i++) {
you also shouldn't assume our robots are only 0 through 5; use `kNumShells`, or, better yet, just use  `world_state.our_robots.size()`

2024-01-29 21:45 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/robot_factory_position.cpp
> +    if (Position::our_possession_ ||
what's the undetermined behavior?

2024-01-31 00:16 UTC, rishiso commented on soccer/src/soccer/strategy/agent/position/robot_factory_position.cpp
> +    if (Position::our_possession_ ||
I noticed that the robots sometimes switched rapidly between offense and defense (probably due to rounding).

2024-01-31 14:41 UTC, sid-parikh approved these changes
hey don't worry about the Goalie fix for now; I worked on that for the Offense PR anyway

2024-01-31 14:41 UTC, sid-parikh commented
your last commit says (not finished) so I'm not hitting merge, but feel free to push it if you're done.

2024-02-05 02:29 UTC, merged