Creates line pivot path planner
RoboJackets/robocup-software pull request #2240
Opened 2024-04-07 23:40 UTC by sanatd33

## Description
Describe your pull request.

## Associated / Resolved Issue
Resolves # or [ClickUp card](link-to-clickup-card)

## Design Documents
[Link](link-to-design-doc)

## Steps to Test
### Test Case 1
1. Step 1
2. Step 2
3. Step 3

**Expected result:**???

## Key Files to Review
Group 1
 * File 1
 * File 2

Group 2
 * File 3
 * File 4

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1
- [ ] Step 2

2024-04-10 03:10 UTC, sid-parikh requested changes
please look at clang-tidy generated warnings in GitHub

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/line_pivot_path_planner.hpp
> +    double IS_DONE_ANGLE_CHANGE_THRESH = 1.0;
```suggestion
    static constexpr double IS_DONE_ANGLE_CHANGE_THRESH {1.0};
```

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/line_pivot_path_planner.cpp
> +    bool val = abs(cached_angle_change_.value()) < degrees_to_radians(IS_DONE_ANGLE_CHANGE_THRESH);
```suggestion
    bool val = abs(cached_angle_change_.value()) < degrees_to_radians(static_cast<float>(IS_DONE_ANGLE_CHANGE_THRESH));
```

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/line_pivot_path_planner.cpp
> +        plan_request.world_state->get_robot(true, plan_request.shell_id).pose.position();
```suggestion
        plan_request.world_state->get_robot(true, static_cast<int>(plan_request.shell_id)).pose.position();
```

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/line_pivot_path_planner.cpp
> +        plan_request.world_state->get_robot(true, plan_request.shell_id).velocity.linear().mag();
```suggestion
        plan_request.world_state->get_robot(true, static_cast<int>(plan_request.shell_id)).velocity.linear().mag();
```

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/line_pivot_path_planner.cpp
> +        plan_request.world_state->get_robot(true, plan_request.shell_id).pose.position();
```suggestion
        plan_request.world_state->get_robot(true, static_cast<int>(plan_request.shell_id)).pose.position();
```

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/line_pivot_path_planner.cpp
> +        request.world_state->get_robot(true, request.shell_id).pose.position());
```suggestion
        request.world_state->get_robot(true, static_cast<int>(request.shell_id)).pose.position());
```

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/pivot_path_planner.cpp
> +    bool val = abs(cached_angle_change_.value()) < degrees_to_radians(IS_DONE_ANGLE_CHANGE_THRESH);
```suggestion
    bool val = abs(cached_angle_change_.value()) < degrees_to_radians(static_cast<float>(IS_DONE_ANGLE_CHANGE_THRESH));
```

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/pivot_test.cpp
> +                } else {
note the GH warning here

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/pivot_test.cpp
> +        case OUR_GOAL: {
clang-tidy wants you to collapse these cases. but i'm okay if you don't. it's up to you

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/pivot_test.hpp
> +class Pivot : public Position {
note the clang-tidy warning you need to define some special member functions  see "rule of five" here https://en.cppreference.com/w/cpp/language/rule_of_three

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/pivot_test.hpp
> +class Pivot : public Position {
note that you can explicitly `= default;` them

2024-04-10 03:10 UTC, sid-parikh commented on soccer/src/soccer/strategy/agent/position/robot_factory_position.cpp
> -        current_position_ = std::make_unique<Goalie>(robot_id_);
uncommit this please

2024-04-21 23:24 UTC, sid-parikh approved these changes, later dismissed

2024-04-24 00:30 UTC, rishiso approved these changes

2024-04-24 01:06 UTC, rishiso commented on soccer/src/soccer/planning/planner/line_pivot_path_planner.cpp
> +    return val;
```suggestion
    return abs(cached_angle_change_.value()) <
               degrees_to_radians(static_cast<float>(is_done_angle_change_thresh_));
```

2024-04-28 22:18 UTC, sid-parikh approved these changes
we need to work on documenting the path planning logic/math

2024-04-28 22:27 UTC, merged