Split Link Kick into 2 Planners
RoboJackets/robocup-software pull request #2242
Opened 2024-04-08 00:32 UTC by Squid5678

## Description
Splits line kick into 2 planners.

## Associated / Resolved Issue
Resolves # or [ClickUp card](link-to-clickup-card)

## Design Documents
[Link](link-to-design-doc)

## Steps to Test
### Test Case 1
1. Step 1
2. Step 2
3. Step 3

**Expected result:**???

## Key Files to Review
Group 1
 * File 1
 * File 2

Group 2
 * File 3
 * File 4

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1
- [ ] Step 2

2024-04-10 03:11 UTC, sid-parikh requested changes
can you fix the two clang-tidy warnings in GH please? just a case style thing

2024-04-10 03:11 UTC, sid-parikh commented on soccer/src/soccer/planning/planner/line_kick_path_planner.hpp
> +    PathTargetPathPlanner initial_planner{};
```suggestion
    PathTargetPathPlanner initial_planner_{};
```

2024-04-10 03:11 UTC, sid-parikh commented
also merge style checks

2024-04-23 21:05 UTC, sanatd33 requested changes

2024-04-23 21:05 UTC, sanatd33 commented on soccer/src/soccer/planning/planner/line_kick_path_planner.cpp
> +    return initial_planner.plan(modified_request);
looks like you missed the underscore after the variable name so it isn't compiling

2024-04-23 21:05 UTC, sanatd33 commented on soccer/src/soccer/planning/planner/line_kick_path_planner.cpp
> +    if (current_state_ == INITIAL_APPROACH && initial_planner.is_done()) {
Same thing here

2024-04-23 21:05 UTC, sanatd33 commented on soccer/src/soccer/planning/planner/line_kick_path_planner.hpp
> +    PathTargetPathPlanner final_planner{};
fix case style by renaming `final_planner` to `final_planner_`

2025-02-17 02:02 UTC, closed without merging