doubled wall spacing
RoboJackets/robocup-software pull request #2282
Opened 2024-09-29 23:41 UTC by piman51277

Completes RC SW Tutorials.

2024-09-29 23:48 UTC, piman51277 commented
![image](https://github.com/user-attachments/assets/2cef3d59-098c-4f78-acc2-5d9e184817de)

2024-10-07 00:42 UTC, piman51277 commented
Evidence of topic publish:
![bananas](https://github.com/user-attachments/assets/c2147324-bf44-4aea-b80d-03baf0e5c68e)
![blueberries](https://github.com/user-attachments/assets/e967e8c2-3c07-42c7-aa03-5a2a62bfb0e6)

2024-10-07 00:43 UTC, piman51277 commented
Feedback:
I liked the tutorial, but it should have included the note about adding to cmake when we had to make a new position.

2024-10-09 00:38 UTC, jacksherling requested changes
Great job overall!

Please review the comments and close this PR when you're finished! Feel free to let me know if you have any questions.

2024-10-09 00:38 UTC, jacksherling commented on soccer/src/soccer/strategy/agent/position/runner.cpp
> +    return current.dist_to(target) < tolerance;
take a look at the `check_is_done` function. When the plan succeeds it returns true. This way thresholding for plans is abstracted away from strategy

2024-10-09 00:38 UTC, jacksherling commented on soccer/src/soccer/strategy/agent/position/runner.cpp
> +bool Runner::shot_on_goal_detected(WorldState* world_state) {
Looks like you left some extra stuff from another position here

2024-10-09 00:38 UTC, jacksherling commented on soccer/src/soccer/strategy/agent/position/runner.hpp
> +        PREPARING_SHOT,  // pivot around ball in preparation for shot
Similar to above, let's remove stuff not used for runner

2024-10-09 00:38 UTC, jacksherling commented on soccer/src/soccer/soccermom/soccermom.cpp
> +    if (blue_team) {
I think this work is already done in the subscription

2024-10-09 00:38 UTC, jacksherling commented on soccer/src/soccer/soccermom/soccermom.cpp
> +                create_publisher<std_msgs::msg::String>("/team_fruit", rclcpp::QoS(10));
why create a new publisher on every subscription callback?

2024-10-09 00:38 UTC, jacksherling commented on soccer/src/soccer/soccermom/soccermom.hpp
> +    std::array<strategy::Positions, kNumShells> positions_;
Let's remove the unused variables here

2024-10-09 00:43 UTC, jacksherling approved these changes

2024-10-09 13:30 UTC, closed without merging