Ball placement obstacle with Stadium Shape on their ball placement
RoboJackets/robocup-software pull request #2294
Opened 2024-10-23 00:48 UTC by shourikb

## Description
Ensure rules compliance during their ball placement by staying out of the restricted area which is a stadium shape. We create a new geometry shape that represents this stadium shape. The stadium shape is composed of 2 circles and a rectangle. To create the shape, it takes in 2 points (that represent the centers of the circles) and a radius.

## Associated / Resolved Issue
https://app.clickup.com/t/86b1vty49

## Steps to Test
### Test Case 1
1. Run external ref
2. Modify robot_factory_position such that update_position always returns SmartIdle
3. Run ball placement for blue team (yellow team should be Robojackets)
4. Place the ball somewhere in the field
5. Move a robot into the stadium shape drawn

**Expected result:**
Robot will move out of stadium shape drawn

## Key Files to Review
Stadium Shape
 * stadium_shape.cpp
 * stadium_shape.hpp

Plan Request
 * plan_request.cpp

Drawer
* ros_debug_drawer.hpp

## Review Checklist

- [ ] **Docstrings**: All methods and classes should have the file appropriate docstrings which follow the guidelines in the ["Contributing" page](https://rj-rc-software.readthedocs.io/en/latest/contributing.html) of our docs.
- [ ] **Remove extra print statements**: Any print statements used for debugging should be removed
- [ ] **Tag reviewers**: Tag some people for review and ping them on Slack

## (Optional) Sub-issues (for drafts)
_Note: if you find yourself breaking this PR into many smaller features, it may make sense to break up the PR into logical units based on these features._
- [ ] Step 1
- [ ] Step 2

2024-10-23 01:05 UTC, sanatd33 requested changes

2024-10-23 01:05 UTC, sanatd33 commented on soccer/src/soccer/debug_drawer.cpp
> +// void DebugDrawer::draw_stadium(rj_geometry::StadiumShape& stadium, const QColor& qc, const QString& layer) {
remove the comments

2024-10-23 01:05 UTC, sanatd33 commented on soccer/src/soccer/debug_drawer.hpp
> +    // void draw_stadium(rj_geometry::StadiumShape& stadium,
here too

2024-10-23 01:05 UTC, sanatd33 commented on soccer/src/soccer/planning/planner/plan_request.cpp
> +            // std::shared_ptr<rj_geometry::Shape> track_obs_ptr = std::make_shared<rj_geometry::Shape>(stadium);
this will be fixed when you add a move constructor

2024-10-23 01:05 UTC, sanatd33 commented on rj_geometry/include/rj_geometry/stadium_shape.hpp
> +
add a move constructor

2024-11-17 23:52 UTC, jacksherling approved these changes

2024-12-16 05:58 UTC, merged